SET gruntLogFilePath=C:\grunt_log\grunt_dc_log.log

call grunt comm2018 >> %gruntLogFilePath%
call grunt Main2018 >> %gruntLogFilePath%
call grunt lotte_product2018 >> %gruntLogFilePath%
call grunt SearchList2018 >> %gruntLogFilePath%
call grunt cart2018 >> %gruntLogFilePath%
call grunt wish2018 >> %gruntLogFilePath%
call grunt MyLotteMain2018 >> %gruntLogFilePath%
call grunt LatelyProduct2018 >> %gruntLogFilePath%
call grunt StylePushIntro2018 >> %gruntLogFilePath%
call grunt Order >> %gruntLogFilePath%
call grunt OrderGift >> %gruntLogFilePath%
call grunt HalfChance >> %gruntLogFilePath%
call grunt BrandSub >> %gruntLogFilePath%
call grunt BrandMain >> %gruntLogFilePath%
call grunt CateMidList >> %gruntLogFilePath%
call grunt CateHolidayMidList >> %gruntLogFilePath%
call grunt CateBeauty >> %gruntLogFilePath%
call grunt CateProdList >> %gruntLogFilePath%
call grunt CateHolidayProdList >> %gruntLogFilePath%
call grunt DeptLive >> %gruntLogFilePath%
call grunt mylotteReinquiryDetail >> %gruntLogFilePath%
call grunt mylotteReinquiryList >> %gruntLogFilePath%
call grunt loginForm >> %gruntLogFilePath%
call grunt findId >> %gruntLogFilePath%
call grunt findIdAfter >> %gruntLogFilePath%
call grunt loginBlock >> %gruntLogFilePath%
call grunt changePw >> %gruntLogFilePath%
call grunt findPw >> %gruntLogFilePath%
call grunt findPwAfter >> %gruntLogFilePath%
call grunt reSendEmail >> %gruntLogFilePath%
call grunt m1200m >> %gruntLogFilePath%
call grunt m1300k >> %gruntLogFilePath%
call grunt specialFlavor >> %gruntLogFilePath%
call grunt SpecialMallMain >> %gruntLogFilePath%
call grunt SpecMall >> %gruntLogFilePath%
call grunt SpecMallSub >> %gruntLogFilePath%
call grunt MallMain >> %gruntLogFilePath%
call grunt book >> %gruntLogFilePath%
call grunt GucciMain >> %gruntLogFilePath%
call grunt lzineList >> %gruntLogFilePath%
call grunt WineDetail >> %gruntLogFilePath%
call grunt ProductWindSmartpic >> %gruntLogFilePath%
call grunt MallSub >> %gruntLogFilePath%
call grunt SmpBooking >> %gruntLogFilePath%
call grunt TvHome >> %gruntLogFilePath%
call grunt ProdList >> %gruntLogFilePath%
call grunt ProdList2 >> %gruntLogFilePath%
call grunt GucciProduct >> %gruntLogFilePath%
call grunt Product >> %gruntLogFilePath%
call grunt dormancyInfoFail >> %gruntLogFilePath%
call grunt dormancyInfo >> %gruntLogFilePath%
call grunt soGoodBenefit >> %gruntLogFilePath%
call grunt directAttend >> %gruntLogFilePath%
call grunt Company >> %gruntLogFilePath%
call grunt CustAgreement >> %gruntLogFilePath%
call grunt CustPrivacy >> %gruntLogFilePath%
call grunt CouponWrite >> %gruntLogFilePath%
call grunt cscenterMain >> %gruntLogFilePath%
call grunt DepositRefund >> %gruntLogFilePath%
call grunt cscenterFaq >> %gruntLogFilePath%
call grunt cscenterNotice >> %gruntLogFilePath%
call grunt SmartPickSend >> %gruntLogFilePath%
call grunt SmartPick >> %gruntLogFilePath%
call grunt smartpick2016 >> %gruntLogFilePath%
call grunt Planshop >> %gruntLogFilePath%
call grunt ProtectYouth >> %gruntLogFilePath%
call grunt SmartPickView >> %gruntLogFilePath%
call grunt PointInfo >> %gruntLogFilePath%
call grunt CashBill >> %gruntLogFilePath%
call grunt EventSaunList >> %gruntLogFilePath%
call grunt EventSaunMain >> %gruntLogFilePath%
call grunt EventInfo >> %gruntLogFilePath%
call grunt EventDetail >> %gruntLogFilePath%
call grunt EventPlanshop >> %gruntLogFilePath%
call grunt evtReview >> %gruntLogFilePath%
call grunt evtTester >> %gruntLogFilePath%
call grunt mylotteCritView >> %gruntLogFilePath%
call grunt commentWrite >> %gruntLogFilePath%
call grunt commentRewrite >> %gruntLogFilePath%
call grunt smartAlarmList >> %gruntLogFilePath%
call grunt answer >> %gruntLogFilePath%
call grunt answerDetail >> %gruntLogFilePath%
call grunt question >> %gruntLogFilePath%
call grunt productQuestWrite >> %gruntLogFilePath%
call grunt productQuestWriteGucci >> %gruntLogFilePath%
call grunt ProductDetailPopUp >> %gruntLogFilePath%
call grunt couponBook >> %gruntLogFilePath%
call grunt emailBargainList >> %gruntLogFilePath%
call grunt emailBargainDetail >> %gruntLogFilePath%
call grunt shoppingMail >> %gruntLogFilePath%
call grunt smpCpnRfdList >> %gruntLogFilePath%
call grunt OrderChangeCancelConf >> %gruntLogFilePath%
call grunt OrderChangeCancelInfo >> %gruntLogFilePath%
call grunt OrderChangeReg1 >> %gruntLogFilePath%
call grunt OrderChangeReg2 >> %gruntLogFilePath%
call grunt OrderChangeReg3 >> %gruntLogFilePath%
call grunt OrderReturnCancelConf >> %gruntLogFilePath%
call grunt OrderReturnCancelInfo >> %gruntLogFilePath%
call grunt OrderReturnReg1 >> %gruntLogFilePath%
call grunt OrderReturnReg2 >> %gruntLogFilePath%
call grunt OrderReturnReg3 >> %gruntLogFilePath%
call grunt OrderComplete >> %gruntLogFilePath%
call grunt OrderCancel >> %gruntLogFilePath%
call grunt smartPay >> %gruntLogFilePath%
call grunt SelectPresent >> %gruntLogFilePath%
call grunt PurchaseView >> %gruntLogFilePath%
call grunt purchase >> %gruntLogFilePath%
call grunt OrdMsgSetting >> %gruntLogFilePath%
call grunt gucciFaq >> %gruntLogFilePath%
call grunt OrderChangeReturnCancelError >> %gruntLogFilePath%
call grunt seed >> %gruntLogFilePath%
call grunt ReceiptEvent >> %gruntLogFilePath%
call grunt appDownKt >> %gruntLogFilePath%
call grunt SktCoupon >> %gruntLogFilePath%
call grunt receipt >> %gruntLogFilePath%
call grunt prsnMail >> %gruntLogFilePath%
call grunt EventSmartpick >> %gruntLogFilePath%
call grunt appDownPriceDown >> %gruntLogFilePath%
call grunt sktDataFree >> %gruntLogFilePath%
call grunt eventAnycar >> %gruntLogFilePath%
call grunt eventKdbLife >> %gruntLogFilePath%
call grunt eventSamsungFire >> %gruntLogFilePath%
call grunt between >> %gruntLogFilePath%
call grunt dotcomStaffBoard >> %gruntLogFilePath%
call grunt dotcomStaffBoardAdmin >> %gruntLogFilePath%
call grunt appDownOcb >> %gruntLogFilePath%
call grunt ProductRent >> %gruntLogFilePath%
call grunt StylePush >> %gruntLogFilePath%
call grunt StyleRecom >> %gruntLogFilePath%
call grunt StyleShop >> %gruntLogFilePath%
call grunt StyleShopMen >> %gruntLogFilePath%
call grunt Katalk >> %gruntLogFilePath%
call grunt BigDeal >> %gruntLogFilePath%
call grunt SamsungDriver >> %gruntLogFilePath%
call grunt FourDays >> %gruntLogFilePath%
call grunt GiftSaun >> %gruntLogFilePath%
call grunt RsaleBest >> %gruntLogFilePath%
call grunt AppDownStaff >> %gruntLogFilePath%
call grunt Shodoc >> %gruntLogFilePath%
call grunt subSmartPick >> %gruntLogFilePath%
call grunt tvShopping2016 >> %gruntLogFilePath%
call grunt subRanking >> %gruntLogFilePath%
call grunt EventComment20th >> %gruntLogFilePath%
call grunt EventCommentHong >> %gruntLogFilePath%
call grunt EventPetLove >> %gruntLogFilePath%
call grunt EventYouthSpring >> %gruntLogFilePath%
call grunt shareEvent >> %gruntLogFilePath%
call grunt EventMeritzCar >> %gruntLogFilePath%
call grunt PresentList >> %gruntLogFilePath%
call grunt PresentDetail >> %gruntLogFilePath%
call grunt PresentComment >> %gruntLogFilePath%
call grunt giftcheck >> %gruntLogFilePath%
call grunt instagramList >> %gruntLogFilePath%
call grunt sslive >> %gruntLogFilePath%
call grunt CvsReturnGuide >> %gruntLogFilePath%
call grunt talk >> %gruntLogFilePath%
call grunt ChanelMain >> %gruntLogFilePath%
call grunt ChanelProdList >> %gruntLogFilePath%
call grunt smart_deli_info >> %gruntLogFilePath%
call grunt DearpetMain >> %gruntLogFilePath%
call grunt DearpetProdList >> %gruntLogFilePath%
call grunt DearpetGallery >> %gruntLogFilePath%
call grunt DearpetNews >> %gruntLogFilePath%
call grunt SwagWrite >> %gruntLogFilePath%
call grunt SwagRewrite >> %gruntLogFilePath%
call grunt ExperienceMain >> %gruntLogFilePath%
call grunt ExperienceWrite >> %gruntLogFilePath%
call grunt ExperienceView >> %gruntLogFilePath%
call grunt ExperienceWinnerList >> %gruntLogFilePath%
call grunt KidscommentWrite >> %gruntLogFilePath%
call grunt photoreview >> %gruntLogFilePath%
call grunt infantMain >> %gruntLogFilePath%
call grunt infantSwagWrite >> %gruntLogFilePath%
call grunt infantSwagRewrite >> %gruntLogFilePath%
call grunt WishRecom >> %gruntLogFilePath%
call grunt BrandSearch >> %gruntLogFilePath%
call grunt customSearchPage >> %gruntLogFilePath%
call grunt StyleShopMain >> %gruntLogFilePath%
call grunt BestBrandMain >> %gruntLogFilePath%
call grunt BestBrandSub >> %gruntLogFilePath%
call grunt TalkRecom >> %gruntLogFilePath%
call grunt TalkShopping >> %gruntLogFilePath%
call grunt TalkShopDelPay >> %gruntLogFilePath%
call grunt TalkShopOrder >> %gruntLogFilePath%
call grunt orderSingle >> %gruntLogFilePath%
call grunt DearpetPetWrite >> %gruntLogFilePath%
call grunt ProductView >> %gruntLogFilePath%
call grunt ProductBenefitCompare >> %gruntLogFilePath%
call grunt ProductCollectBenefits >> %gruntLogFilePath%
call grunt ProductComment >> %gruntLogFilePath%
call grunt ProductCommentDetail >> %gruntLogFilePath%
call grunt ProductExtInfo >> %gruntLogFilePath%
call grunt ProductImageView >> %gruntLogFilePath%
call grunt ProductQna >> %gruntLogFilePath%
call grunt ProductReqInfo >> %gruntLogFilePath%
call grunt productMdNoticeWebview >> %gruntLogFilePath%
call grunt productDetailInfoWebview >> %gruntLogFilePath%
call grunt productPlanDetailInfoTopWebview >> %gruntLogFilePath%
call grunt productPlanDetailInfoBottomWebview >> %gruntLogFilePath%
call grunt lpayWebMng >> %gruntLogFilePath%
call grunt movieStore >> %gruntLogFilePath%
call grunt movieReview >> %gruntLogFilePath%
call grunt cartPush >> %gruntLogFilePath%
call grunt MitouStoryDetail >> %gruntLogFilePath%
call grunt MitouStory >> %gruntLogFilePath%
call grunt MitouAdvice >> %gruntLogFilePath%
call grunt bestSamsungMain >> %gruntLogFilePath%
call grunt bestSamsungSub >> %gruntLogFilePath%
call grunt MyFeed >> %gruntLogFilePath%
call grunt OftenBuy >> %gruntLogFilePath%
call grunt ReOrder >> %gruntLogFilePath%
call grunt largeOrder >> %gruntLogFilePath%
call grunt SpecMallDetail >> %gruntLogFilePath%
call grunt SpecMallDetailProduct >> %gruntLogFilePath%
call grunt voiceOrder >> %gruntLogFilePath%
call grunt searchPlanShopList >> %gruntLogFilePath%
call grunt VoiceCommerce >> %gruntLogFilePath%
call grunt UsedMain >> %gruntLogFilePath%
call grunt UsedWrite >> %gruntLogFilePath%
call grunt UsedInfo >> %gruntLogFilePath%
call grunt ProductCommentImage >> %gruntLogFilePath%
call grunt ProductCommentEach >> %gruntLogFilePath%
call grunt burberryMain >> %gruntLogFilePath%
call grunt burberryProdList >> %gruntLogFilePath%
call grunt burberryCscenter >> %gruntLogFilePath%
call grunt ProductViewBurberry >> %gruntLogFilePath%
call grunt orderSimple >> %gruntLogFilePath%
call grunt orderSimpleComplete >> %gruntLogFilePath%
call grunt dearpetBrdBest >> %gruntLogFilePath%
call grunt ProfileWrite >> %gruntLogFilePath%
call grunt ReviewBest >> %gruntLogFilePath%
call grunt ReviewFavorite >> %gruntLogFilePath%
call grunt ReviewerHome >> %gruntLogFilePath%
call grunt ssoDropGate >> %gruntLogFilePath%
call grunt couponzone >> %gruntLogFilePath%
