#!/bin/bash

grunt comm2018
grunt Main2018
grunt lotte_product2018
grunt SearchList2018
grunt cart2018
grunt wish2018
grunt MyLotteMain2018
grunt LatelyProduct2018
grunt StylePushIntro2018
grunt Order
grunt OrderGift
grunt HalfChance
grunt BrandSub
grunt BrandMain
grunt CateMidList
grunt CateHolidayMidList
grunt CateBeauty
grunt CateProdList
grunt CateHolidayProdList
grunt DeptLive
grunt mylotteReinquiryDetail
grunt mylotteReinquiryList
grunt loginForm
grunt findId
grunt findIdAfter
grunt loginBlock
grunt changePw
grunt findPw
grunt findPwAfter
grunt reSendEmail
grunt m1200m
grunt m1300k
grunt specialFlavor
grunt SpecialMallMain
grunt SpecMall
grunt SpecMallSub
grunt MallMain
grunt book
grunt GucciMain
grunt lzineList
grunt WineDetail
grunt ProductWindSmartpic
grunt MallSub
grunt SmpBooking
grunt TvHome
grunt ProdList
grunt ProdList2
grunt GucciProduct
grunt Product
grunt dormancyInfoFail
grunt dormancyInfo
grunt soGoodBenefit
grunt directAttend
grunt Company
grunt CustAgreement
grunt CustPrivacy
grunt CouponWrite
grunt cscenterMain
grunt DepositRefund
grunt cscenterFaq
grunt cscenterNotice
grunt SmartPickSend
grunt SmartPick
grunt smartpick2016
grunt Planshop
grunt ProtectYouth
grunt SmartPickView
grunt PointInfo
grunt CashBill
grunt EventSaunList
grunt EventSaunMain
grunt EventInfo
grunt EventDetail
grunt EventPlanshop
grunt evtReview
grunt evtTester
grunt mylotteCritView
grunt commentWrite
grunt commentRewrite
grunt smartAlarmList
grunt answer
grunt answerDetail
grunt question
grunt productQuestWrite
grunt productQuestWriteGucci
grunt ProductDetailPopUp
grunt couponBook
grunt emailBargainList
grunt emailBargainDetail
grunt shoppingMail
grunt smpCpnRfdList
grunt OrderChangeCancelConf
grunt OrderChangeCancelInfo
grunt OrderChangeReg1
grunt OrderChangeReg2
grunt OrderChangeReg3
grunt OrderReturnCancelConf
grunt OrderReturnCancelInfo
grunt OrderReturnReg1
grunt OrderReturnReg2
grunt OrderReturnReg3
grunt OrderComplete
grunt OrderCancel
grunt smartPay
grunt SelectPresent
grunt PurchaseView
grunt purchase
grunt OrdMsgSetting
grunt gucciFaq
grunt OrderChangeReturnCancelError
grunt seed
grunt ReceiptEvent
grunt appDownKt
grunt SktCoupon
grunt receipt
grunt prsnMail
grunt EventSmartpick
grunt appDownPriceDown
grunt sktDataFree
grunt eventAnycar
grunt eventKdbLife
grunt eventSamsungFire
grunt between
grunt dotcomStaffBoard
grunt dotcomStaffBoardAdmin
grunt appDownOcb
grunt ProductRent
grunt StylePush
grunt StyleRecom
grunt StyleShop
grunt StyleShopMen
grunt Katalk
grunt BigDeal
grunt SamsungDriver
grunt FourDays
grunt GiftSaun
grunt RsaleBest
grunt AppDownStaff
grunt Shodoc
grunt subSmartPick
grunt tvShopping2016
grunt subRanking
grunt EventComment20th
grunt EventCommentHong
grunt EventPetLove
grunt EventYouthSpring
grunt shareEvent
grunt EventMeritzCar
grunt PresentList
grunt PresentDetail
grunt PresentComment
grunt giftcheck
grunt instagramList
grunt sslive
grunt CvsReturnGuide
grunt talk
grunt ChanelMain
grunt ChanelProdList
grunt smart_deli_info
grunt DearpetMain
grunt DearpetProdList
grunt DearpetGallery
grunt DearpetNews
grunt SwagWrite
grunt SwagRewrite
grunt ExperienceMain
grunt ExperienceWrite
grunt ExperienceView
grunt ExperienceWinnerList
grunt KidscommentWrite
grunt photoreview
grunt infantMain
grunt infantSwagWrite
grunt infantSwagRewrite
grunt WishRecom
grunt BrandSearch
grunt customSearchPage
grunt StyleShopMain
grunt BestBrandMain
grunt BestBrandSub
grunt TalkRecom
grunt TalkShopping
grunt TalkShopDelPay
grunt TalkShopOrder
grunt orderSingle
grunt DearpetPetWrite
grunt ProductView
grunt ProductBenefitCompare
grunt ProductCollectBenefits
grunt ProductComment
grunt ProductCommentDetail
grunt ProductExtInfo
grunt ProductImageView
grunt ProductQna
grunt ProductReqInfo
grunt productMdNoticeWebview
grunt productDetailInfoWebview
grunt productPlanDetailInfoTopWebview
grunt productPlanDetailInfoBottomWebview
grunt lpayWebMng
grunt movieStore
grunt movieReview
grunt cartPush
grunt MitouStoryDetail
grunt MitouStory
grunt MitouAdvice
grunt bestSamsungMain
grunt bestSamsungSub
grunt MyFeed
grunt OftenBuy
grunt ReOrder
grunt largeOrder
grunt SpecMallDetail
grunt SpecMallDetailProduct
grunt voiceOrder
grunt searchPlanShopList
grunt VoiceCommerce
grunt UsedMain
grunt UsedWrite
grunt UsedInfo
grunt ProductCommentImage
grunt ProductCommentEach
grunt burberryMain
grunt burberryProdList
grunt burberryCscenter
grunt ProductViewBurberry
grunt orderSimple
grunt orderSimpleComplete 
grunt dearpetBrdBest
grunt ProfileWrite
grunt ReviewBest
grunt ReviewFavorite
grunt ReviewerHome
grunt ssoDropGate
grunt couponzone
