<%@ page contentType="application/json; charset=UTF-8" %>
<%
int getpage = Integer.parseInt(request.getParameter("page"));
String keyword = request.getParameter("keyword");
String rtnType = request.getParameter("rtnType");
String sorting = request.getParameter("sort");

if(keyword == null){ keyword = ""; }
if(rtnType == null){ rtnType = ""; }
if(sorting == null){ sorting = "RANK,1"; }

if(keyword.indexOf("empty")<0){
%>
{
"max":{
   "resultCode": "0000",
   "dispCnt": "30",
   "page": <%= getpage %>,
   <% if(!(rtnType.equals("P") || rtnType.equals("S"))){ %>
   "tCnt": <%= (int) (Math.random() * 100000) %>,
   <% } %>
	"price": {
		"min": "2850",
		"max": "259200"
	},
   "prdLst": {
      "items": [{
         "is_himart": false,
         "brnd_nm": "도날드",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "194622876",
         "is_sale_promotion": true,
         "goods_nm": "<%= getpage %> 페이지 첫번째 상품 - 도날드 세일러 원피스 (AF4GO780)",
         "is_dept": false,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/17\/24\/41\/39\/2\/239412417_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "EC",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5418800",
         "discounted_price": 90250,
         "is_tvhome": false,
         "original_price": 95000,
         "hash_list":["나들이룩", "바캉스룩", "피크닉룩"],
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":"",
         "isCrsPickYn":"Y",
         "isDeptPickYn":"Y",
         "isDlvQuick":"Y",
         "isDlvToday":"Y"
      }, {
         "is_himart": false,
         "brnd_nm": "뉴발란스",
         "sale_rate": 0,
         "has_coupon": false,
         "outlnk": "",
         "goods_no": "187173018",
         "is_sale_promotion": false,
         "goods_nm": "2015FW 다운자켓 NBNP544031 MEN 2015 패트롤 다운자켓",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/18\/30\/17\/87\/1\/187173018_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "5",
         "limit_age_yn": "N",
         "curDispNo": "5420067",
         "discounted_price": 456800,
         "is_tvhome": false,
         "original_price": 459000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "컬럼비아",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "196144640",
         "is_sale_promotion": true,
         "goods_nm": "기능성 최고! 디자인도 GOOD! 인기 컬럼비아!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/40\/46\/14\/96\/1\/196144640_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 115370,
         "is_tvhome": false,
         "original_price": 139000,
         "hash_list": [
            "하지원 가방",
            "명품가방",
            "CHOLOE",
            "가죽토드백",
            "하지원 가방",
            "명품가방",
            "CHOLOE",
            "가죽토드백"
         ],
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "르까프",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "187101265",
         "is_sale_promotion": false,
         "goods_nm": "어느 옷에도 소화가능한 보온성이 뛰어난 야상덕다운1214HS401 402 403 451 452 453",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/65\/12\/10\/87\/1\/187101265_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "2",
         "limit_age_yn": "N",
         "curDispNo": "5420067",
         "discounted_price": 84150,
         "is_tvhome": false,
         "original_price": 99000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "노스페이스화이트라벨(프리미엄)",
         "sale_rate": 10,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "193586676",
         "is_sale_promotion": true,
         "goods_nm": "아론,넬슨 노벨티,AK 外 다운자켓 추천!!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/76\/66\/58\/93\/1\/193586676_5_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420066",
         "discounted_price": 248900,
         "is_tvhome": false,
         "original_price": 278000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "코오롱스포츠(의류)",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "199234517",
         "is_sale_promotion": false,
         "goods_nm": "(TLJDW15201EDM) TRAVEL 동절 남성 사파리 다운자켓",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/17\/45\/23\/99\/1\/199234517_3_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 218650,
         "is_tvhome": false,
         "original_price": 265000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "블랙야크",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "191898873",
         "is_sale_promotion": true,
         "goods_nm": "겨울에도 스타일 살려주는 16종 택1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/73\/88\/89\/91\/1\/191898873_2_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5419967",
         "discounted_price": 180500,
         "is_tvhome": false,
         "original_price": 190000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "밀레(아웃도어)",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "200505916",
         "is_sale_promotion": true,
         "goods_nm": "밀레 다운 입고 춥지않고 따뜻하게 보내자!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/16\/59\/50\/00\/2\/200505916_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 123670,
         "is_tvhome": false,
         "original_price": 149000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "라푸마",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "177612063",
         "is_sale_promotion": false,
         "goods_nm": "[다운조끼 증정]남\/여 EVER(에버) FresHeat 구스다운 점퍼[LMJ05D867,LFJ05D867]",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/63\/20\/61\/77\/1\/177612063_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "12",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 235510,
         "is_tvhome": false,
         "original_price": 278600,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "네파(아웃도어)",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "190783593",
         "is_sale_promotion": true,
         "goods_nm": "추위에도 걱정없는 다운 2종 택1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/93\/35\/78\/90\/1\/190783593_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5419967",
         "discounted_price": 185650,
         "is_tvhome": false,
         "original_price": 225000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "아디다스 오리지날",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "198909527",
         "is_sale_promotion": true,
         "goods_nm": "겨울맞이 인기 구스다운 할인전! 겨울을 즐길수 있는 아이템들 모두모여라~",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/27\/95\/90\/98\/1\/198909527_10_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420066",
         "discounted_price": 169150,
         "is_tvhome": false,
         "original_price": 199000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "코오롱스포츠",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "191645677",
         "is_sale_promotion": true,
         "goods_nm": "추운건 질색? 그러면 선택해! 코오롱 긴기장 다운모음!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/77\/56\/64\/91\/1\/191645677_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420349",
         "discounted_price": 311900,
         "is_tvhome": false,
         "original_price": 330000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "휠라(아웃도어)",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "185191131",
         "is_sale_promotion": true,
         "goods_nm": "다운\/자켓\/베스트\/티셔츠\/팬츠\/트레킹화 17종 택1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/31\/11\/19\/85\/1\/185191131_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5419967",
         "discounted_price": 67150,
         "is_tvhome": false,
         "original_price": 79000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "케이투",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "196791720",
         "is_sale_promotion": true,
         "goods_nm": "추위에 떨지않는 겨울을 위해! 겨울상품 모음!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/20\/17\/79\/96\/1\/196791720_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 278050,
         "is_tvhome": false,
         "original_price": 329000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "빈폴아웃도어",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "201414883",
         "is_sale_promotion": true,
         "goods_nm": "[빈폴아웃도어]김수현이 추천하는 겨울인기 도브다운 20종 점퍼\/경량다운\/자켓\/도브다운",
         "is_dept": false,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/03\/19\/26\/99\/1\/199261903_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "EC",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5419059",
         "discounted_price": 55860,
         "is_tvhome": false,
         "original_price": 58800,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "디스커버리",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "199261903",
         "is_sale_promotion": true,
         "goods_nm": "[디스커버리]겨울아우터&자켓 8종 택1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/03\/19\/26\/99\/1\/199261903_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5419967",
         "discounted_price": 172400,
         "is_tvhome": false,
         "original_price": 204000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "아디다스 오리지날",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "192169626",
         "is_sale_promotion": false,
         "goods_nm": "배지&덕 다운 패딩파카(AC0506,AC0507,AH5751,AH5752,AH5753)",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/26\/96\/16\/92\/1\/192169626_9_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "2",
         "limit_age_yn": "N",
         "curDispNo": "5420067",
         "discounted_price": 218950,
         "is_tvhome": false,
         "original_price": 259000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "휠라 아웃도어",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "98755246",
         "is_sale_promotion": false,
         "goods_nm": "(14년 상품) 남.여 코트형 롱다운점퍼 (O2DJW793.4) 양말+버프증정",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/46\/52\/75\/98\/98755246_12_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "25",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 84150,
         "is_tvhome": false,
         "original_price": 99000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "컬럼비아",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "190561746",
         "is_sale_promotion": false,
         "goods_nm": "2015 신상 방수 옴니테크, 보온성최상 옴니히트 야상스타일 다운자켓 CV4WE4120",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/46\/17\/56\/90\/1\/190561746_12_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "31",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 115370,
         "is_tvhome": false,
         "original_price": 139000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "노스페이스",
         "sale_rate": 20,
         "has_coupon": false,
         "outlnk": "",
         "goods_no": "186814909",
         "is_sale_promotion": false,
         "goods_nm": "남,여 스펙트럼 다운 자켓 [NFJ1DF58,NFJ1DF87] SPECTRUM DOWN JACKET",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/09\/49\/81\/86\/1\/186814909_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "26",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 234100,
         "is_tvhome": false,
         "original_price": 235200,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "빈폴아웃도어",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "192579911",
         "is_sale_promotion": false,
         "goods_nm": "[사은품증정]15FW 인기상품 김수현다운 도브다운 6종 택1 BO5838018",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/11\/99\/57\/92\/1\/192579911_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "5",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 281700,
         "is_tvhome": false,
         "original_price": 298000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "블랙야크",
         "sale_rate": 17,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "32441726",
         "is_sale_promotion": false,
         "goods_nm": "15년 FW 신상품 라쿤퍼 L퍼지다운자켓#1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/26\/17\/44\/32\/32441726_3_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "7",
         "limit_age_yn": "N",
         "curDispNo": "5419967",
         "discounted_price": 198000,
         "is_tvhome": false,
         "original_price": 240000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "노스페이스 화이트라벨",
         "sale_rate": 0,
         "has_coupon": false,
         "outlnk": "",
         "goods_no": "191955184",
         "is_sale_promotion": false,
         "goods_nm": "남여 공용 등산 캐주얼 신소재 브이엑스 맥머도 파카 다운 자켓 NVJ3NG50",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/84\/51\/95\/91\/1\/191955184_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "3",
         "limit_age_yn": "N",
         "curDispNo": "5420067",
         "discounted_price": 268700,
         "is_tvhome": false,
         "original_price": 270000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "노스페이스 화이트라벨",
         "sale_rate": 0,
         "has_coupon": false,
         "outlnk": "",
         "goods_no": "191954980",
         "is_sale_promotion": false,
         "goods_nm": "남성 등산 캐주얼 맥머도 15 다운 파카 기능성 구스 다운 패딩 자켓 NVJ1DG55",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/80\/49\/95\/91\/1\/191954980_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420067",
         "discounted_price": 417900,
         "is_tvhome": false,
         "original_price": 420000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "네파 이젠벅",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "190048183",
         "is_sale_promotion": false,
         "goods_nm": "퀀볼 롱패딩 [BB80903]",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/83\/81\/04\/90\/1\/190048183_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "1",
         "limit_age_yn": "N",
         "curDispNo": "5420349",
         "discounted_price": 94050,
         "is_tvhome": false,
         "original_price": 99000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "험멜",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "198861967",
         "is_sale_promotion": false,
         "goods_nm": "[험멜코리아] 다운 패딩 HM-W6997,HM-W6986,HM-W6999,HM-W6998,HM-6983",
         "is_dept": false,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/67\/19\/86\/98\/1\/198861967_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "EC",
         "review_count": "1",
         "limit_age_yn": "N",
         "curDispNo": "5418800",
         "discounted_price": 46550,
         "is_tvhome": false,
         "original_price": 49000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "빈폴아웃도어",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "183371246",
         "is_sale_promotion": false,
         "goods_nm": "15 FW 김수현다운 신상 도브다운 6종 택1 BO5838018",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/46\/12\/37\/83\/1\/183371246_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": true,
         "outlnkMall": "D",
         "review_count": "13",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 281700,
         "is_tvhome": false,
         "original_price": 298000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "블랙야크",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "191937562",
         "is_sale_promotion": true,
         "goods_nm": "추운겨울 NO 블랙야크로 따뜻하게! 인기다운 택1",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/62\/75\/93\/91\/1\/191937562_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420319",
         "discounted_price": 211300,
         "is_tvhome": false,
         "original_price": 250000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "데상트(의류)",
         "sale_rate": 5,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "183345717",
         "is_sale_promotion": false,
         "goods_nm": "데상트 트레이닝 덕다운 점퍼 남녀공용  [S5423TDJ10]",
         "is_dept": false,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/17\/57\/34\/83\/1\/183345717_1_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "EC",
         "review_count": "12",
         "limit_age_yn": "N",
         "curDispNo": "5418800",
         "discounted_price": 263750,
         "is_tvhome": false,
         "original_price": 279000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }, {
         "is_himart": false,
         "brnd_nm": "아디다스 오리지날",
         "sale_rate": 15,
         "has_coupon": true,
         "outlnk": "",
         "goods_no": "194625385",
         "is_sale_promotion": true,
         "goods_nm": "따뜻한 겨울을 보낼수있는 다운 파카 최고 20% 할인이벤트!",
         "is_dept": true,
         "is_youngplz": false,
         "img_url": "http:\/\/image.lotte.com\/goods\/85\/53\/62\/94\/1\/194625385_9_280.jpg",
         "flag": "",
         "isdlex_free":true,
         "smartpick_yn": false,
         "outlnkMall": "D",
         "review_count": "0",
         "limit_age_yn": "N",
         "curDispNo": "5420066",
         "discounted_price": 41650,
         "is_tvhome": false,
         "original_price": 49000,
         "img_url_550":"",
         "is_sold_out":false,
         "has_wish":false,
         "bought_cum":0,
         "md_tip":"",
         "promotion_text":"",
         "sold_out_cd_yn":"N",
         "link_url":""
      }],
      "tcnt": 30
   }
}
}
<% }else{ %>
{
"max":{
	"resultCode":"1000",
	"dispCnt":"30",
	"tCnt":0,
	"prdLst":{},
	"prdDealLst":{},
	"missKeyword":{"cnt":"0","keyword":""},
	"favLst":{
		"items":[{
			"rank":"NEW",
			"keyword":"스킨푸드"
		},{
			"rank":"NEW",
			"keyword":"bnx"
		},{
			"rank":"NEW",
			"keyword":"접시"
		},{
			"rank":"NEW",
			"keyword":"si"
		},{
			"rank":"60",
			"keyword":"무스탕"
		},{
			"rank":"NEW",
			"keyword":"게스청바지"
		},{
			"rank":"NEW",
			"keyword":"겔랑"
		},{
			"rank":"NEW",
			"keyword":"오설록"
		},{
			"rank":"57",
			"keyword":"크로스백"
		},{
			"rank":"NEW",
			"keyword":"트레이닝복세트"
		}],
		"date":"20160115110803"
	}
}
}
<% } %>