<%@ page contentType="application/json; charset=UTF-8" %>
<%
int getpage = Integer.parseInt(request.getParameter("page"));
String keyword = request.getParameter("keyword");
String rtnType = request.getParameter("rtnType");
String sorting = request.getParameter("sort");
String voice = request.getParameter("isVoice");
String pop_str = request.getParameter("pop");
String chkTypo = request.getParameter("chkTypo");

if(keyword == null){ keyword = ""; }
if(rtnType == null){ rtnType = ""; }
if(sorting == null){ sorting = "RANK,1"; }
if(pop_str == null){ pop_str = ""; }
if(chkTypo == null){ chkTypo = "Y"; }

String[] pop_arr = new String[2];
pop_arr[0] = "";
pop_arr[1] = "";
if(pop_str.equals("")){}else{
	pop_arr = pop_str.split(",");
}

boolean isModify = false;
boolean isVoice = false;
boolean redirectUrl = false;
if(voice.equals("Y") || voice.equals("T")){
	// 음성검색
	if(keyword.indexOf("마이롯데")>=0){
		// 키워드 URL 포워딩
		redirectUrl = true;
	}else{
		// 일반 음성검색
		isVoice = true;
	}	
}

if(keyword.equals("우너피스") && chkTypo.equals("Y")){
	isModify = true;
	keyword = "원피스";
}


if(keyword.indexOf("nodata")<0){
// 검색결과 있는 경우
%>
{
   "resultCode": "0000",
	<%
	if(redirectUrl){
	// 키워드 URL 포워딩
	%>
	"isVoice": "Y",
	"redirectUrl":"/mylotte/m/mylotte_dev.html",
	<%
	}else if(isVoice){
	// 음성검색
	%>
	"isVoice": "T",
	"redirectUrl":"",
	"voiceParams":{
		"VBrdNm":"나이키",
		"VPriceMaxU":"199999",
		"VPriceMinU":"100000",
		"VSmpickYN":"Y",
		"VColorCd":"030",
		"VSmpickBranchNo":"11054",
		"VDelSevenYN":"Y",
		"VKeyword":""
	},
	"ageGndrGrpLst":{},
	<%
	}else{
	// 일반 검색
	%>
	"isVoice": "N",
	"redirectUrl":"",
	<% } %>
	"dispCnt": "30",
	"page": <%= getpage %>,
	"ageGndrGrpLst":{
		"items":[
			{"age":"20","gender":"F"},
			{"age":"20","gender":"M"},
			{"age":"30","gender":"F"},
			{"age":"30","gender":"M"},
			{"age":"40","gender":"F"},
			{"age":"40","gender":"M"}
		],
		"tcnt":6
	},
	"dispUnitType":"<%
		if(keyword.indexOf("원피스")>=0){// 큐레이션 타입 %>01<% }
		else if(keyword.indexOf("립스틱")>=0){// 리뷰 타입 %>02<% }
	%>",
	
	<%
	if(!(rtnType.equals("P") || rtnType.equals("S"))){// 전체 상품개수 표시
		if(chkTypo.equals("N")){ %>
		"tCnt": 1,
		<% }else{ %>
		"tCnt": 1250,
		<% }
	}
	
	// 상품목록 시작
	%>
	<% if(chkTypo.equals("N")){ %>
	"prdLst": {
		"items": [{
		"isHimart": false,
		"brandNm": "[RTN-'<%=rtnType%>' | SRT-'<%=sorting%>']",
		"saleRate": "5",
		"useCpn": "coupon",
		"outlnk": "",
		"goodsNo": "194622876",
		"goodsCmpsCd": "30",
		"goodsNm": "<%= getpage %> <%if(pop_arr!=null){%><%= pop_arr[0] %><%= pop_arr[1] %><%}%> 페이지 첫번째 상품 - 도날드 세일러 원피스 (AF4GO780)",
		"isDept": false,
		"isYoung": false,
		"isSuper": false,
		"isCrsPickYn":true,
		"isDeptPickYn":true,
		"isDlvQuick":true,
		"isDlvToday":true,
		"isSmpick":true,
		"soldout_yn":"Y",
		"imgUrl": "http:\/\/image.lotte.com\/goods\/17\/24\/41\/39\/2\/239412417_1_280.jpg",
		"flag": [],
		"isSmpick": false,
		"outlnkMall": "EC",
		"reviewCnt": "0",
		"byrAgelmt": "0",
		"curDispNo": "5418800",
		"price2": 90250,
		"isTvhome": false,
		"price1": 95000,
		"hash_list":["나들이룩", "바캉스룩", "피크닉룩"],
		"gdasInfo1":{
			"gdasCont":"빠른 배송 감사해요~~~ 자주 이용할께요~~ 다른상품도 써보고싶은데 샘플로 받아볼 수 있을까요?",
			"gdasNo":"67729670"
		},
		"gdasInfo2":{
			"gdasCont":"브랜드데이,기획세트 구성대로 왔아요.차일피일 미루다 샀는데 피부가 먼저 아네요.",
			"gdasNo":"67729671"
		},
		"avg_gdas_stfd_val":"4.1",
		"reviewCnt":6,
		<% if(pop_arr[0].equals("")){// 나이성별 모아보기 없는 경우 %>
		"find_age":"40",
		"find_gender":"M"
		<% }else{// 나이성별 모아보기 있는 경우 %>
		"find_age":"<%=pop_arr[0]%>",
		"find_gender":"<%=pop_arr[1]%>"
		<% } %>
		}],
		"tcnt": 1
	}
	<% }else{ %>
	"prdLst": {
		"items": [{
			"isHimart": false,
			"brandNm": "[RTN-'<%=rtnType%>' | SRT-'<%=sorting%>']",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "194622876",
			"goodsCmpsCd": "30",
			"goodsNm": "<%= getpage %> <%if(pop_arr!=null){%><%= pop_arr[0] %><%= pop_arr[1] %><%}%> 페이지 첫번째 상품 - 도날드 세일러 원피스 (AF4GO780)",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"isCrsPickYn":true,
			"isDeptPickYn":true,
			"isDlvQuick":true,
			"isDlvToday":true,
			"isSmpick":true,
			"soldout_yn":"Y",
			"imgUrl": "http:\/\/image.lotte.com\/goods\/17\/24\/41\/39\/2\/239412417_1_280.jpg",
			"flag": [],
			"isSmpick": false,
			"outlnkMall": "EC",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5418800",
			"price2": 90250,
			"isTvhome": false,
			"price1": 95000,
			"hash_list":["나들이룩", "바캉스룩", "피크닉룩"],
			"gdasInfo1":{
				"gdasCont":"빠른 배송 감사해요~~~ 자주 이용할께요~~ 다른상품도 써보고싶은데 샘플로 받아볼 수 있을까요?",
				"gdasNo":"67729670"
			},
			"gdasInfo2":{
				"gdasCont":"브랜드데이,기획세트 구성대로 왔아요.차일피일 미루다 샀는데 피부가 먼저 아네요.",
				"gdasNo":"67729671"
			},
			"avg_gdas_stfd_val":"4.1",
			"reviewCnt":6,
			"vodUrl": "http://api.wecandeo.com/video/default/BOKNS9AQWrGH7isSpatvKXmlwNOz6xais32ipGaVrwo3eBQkw7tiiajSSiiho4pqLKNis4ZCy4IG7kZTQ431147TteoAieie||",
			<% if(pop_arr[0].equals("")){// 나이성별 모아보기 없는 경우 %>
			"find_age":"40",
			"find_gender":"M"
			<% }else{// 나이성별 모아보기 있는 경우 %>
			"find_age":"<%=pop_arr[0]%>",
			"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[뉴발란스]",
			"saleRate": "0",
			"useCpn": "",
			"outlnk": "",
			"goodsNo": "187173018",
			"goodsCmpsCd": "50",
			"goodsNm": "2015FW 다운자켓 NBNP544031 MEN 2015 패트롤 다운자켓",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/18\/30\/17\/87\/1\/187173018_1_280.jpg",
			"vodUrl":"http://api.wecandeo.com/video/default/BOKNS9AQWrEBM0CCGsEelx1l5quSW2ZipS1NTo5isj0YipZWnIrh1jAUCho4pqLKNis4ZCy4IG7kZTQ431147TteoAieie",
			"flag": [],
			"isSmpick": true,
			"isDeptPickYn":true,
			"outlnkMall": "D",
			"reviewCnt": "5",
			"byrAgelmt": "0",
			"curDispNo": "5420067",
			"price2": 23456800,
			"isTvhome": false,
			"price1": 23459000,
			"gdasInfo1":{
				"gdasCont":"빠른 배송 감사해요~~~ 자주 이용할께요~~ 다른상품도 써보고싶은데 샘플로 받아볼 수 있을까요?",
				"gdasNo":"67729672"
			},
			"gdasInfo2":{},
			"avg_gdas_stfd_val":"4.6",
			"reviewCnt":8,
			"nint_card_flag":"무이자6",
			<% if(pop_arr[0].equals("")){ %>
			"find_age":"20",
			"find_gender":"F"
			<% }else{ %>
			"find_age":"<%=pop_arr[0]%>",
			"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[컬럼비아]",
			"saleRate": "17",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "196144640",
			"goodsCmpsCd": "30",
			"goodsNm": "기능성 최고! 디자인도 GOOD! 인기 컬럼비아!",
			"isDept": false,
			"isYoung": false,
			"isSuper": true,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/40\/46\/14\/96\/1\/196144640_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"soldout_yn":"Y",
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 115370,
			"isTvhome": false,
			"price1": 139000,
			"outlnk":"http://m.lottesuper.co.kr/handler/goods/GoodsDetail?AFCR_TRK=Y&goods_no=1376035&CHL_NO=M384143",
			"outlnkMall":"SP",
			"hash_list": [
			"하지원 가방",
			"명품가방",
			"CHOLOE",
			"가죽토드백",
			"하지원가방",
			"명품가방",
			"CHOLOE",
			"가죽토드백"
			],
			"avg_gdas_stfd_val":"3.2",
			"reviewCnt":12
			<% if(pop_arr[0].equals("")==false){ %>
			,"find_age":"<%=pop_arr[0]%>"
			,"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[르까프]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "187101265",
			"goodsCmpsCd": "50",
			"goodsNm": "어느 옷에도 소화가능한 보온성이 뛰어난 야상덕다운1214HS401 402 403 451 452 453",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/65\/12\/10\/87\/1\/187101265_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "2",
			"byrAgelmt": "0",
			"curDispNo": "5420067",
			"price2": 84150,
			"isTvhome": false,
			"price1": 99000,
			"gdasInfo1":{
				"gdasCont":"빠른 배송 감사해요~~~ 자주 이용할께요~~ 다른상품도 써보고싶은데 샘플로 받아볼 수 있을까요?",
				"gdasNo":"67729673"
			},
			"gdasInfo2":{
				"gdasCont":"브랜드데이,기획세트 구성대로 왔아요.차일피일 미루다 샀는데 피부가 먼저 아네요.",
				"gdasNo":"67729674"
			}
			<% if(pop_arr[0].equals("")==false){ %>
			,"find_age":"<%=pop_arr[0]%>"
			,"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[노스페이스화이트라벨(프리미엄)]",
			"saleRate": "10",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "193586676",
			"goodsCmpsCd": "30",
			"goodsNm": "아론,넬슨 노벨티,AK 外 다운자켓 추천!!",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/76\/66\/58\/93\/1\/193586676_5_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420066",
			"price2": 248900,
			"isTvhome": false,
			"price1": 278000
			<% if(pop_arr[0].equals("")==false){ %>
			,"find_age":"<%=pop_arr[0]%>"
			,"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[코오롱스포츠(의류)]",
			"saleRate": "17",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "199234517",
			"goodsCmpsCd": "50",
			"goodsNm": "(TLJDW15201EDM) TRAVEL 동절 남성 사파리 다운자켓",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/17\/45\/23\/99\/1\/199234517_3_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 218650,
			"isTvhome": false,
			"price1": 265000,
			"gdasInfo1":{
				"gdasCont":"빠른 배송 감사해요~~~ 자주 이용할께요~~ 다른상품도 써보고싶은데 샘플로 받아볼 수 있을까요?",
				"gdasNo":"67729674"
			},
			"gdasInfo2":{
				"gdasCont":"브랜드데이,기획세트 구성대로 왔아요.차일피일 미루다 샀는데 피부가 먼저 아네요.",
				"gdasNo":"67729675"
			}
			<% if(pop_arr[0].equals("")==false){ %>
			,"find_age":"<%=pop_arr[0]%>"
			,"find_gender":"<%=pop_arr[1]%>"
			<% } %>
		},{
			"isHimart": false,
			"brandNm": "[블랙야크]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "191898873",
			"goodsCmpsCd": "30",
			"goodsNm": "스타일 16종 택1",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/73\/88\/89\/91\/1\/191898873_2_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5419967",
			"price2": 180500,
			"isTvhome": false,
			"price1": 190000,
			"avg_gdas_stfd_val":"4.6",
			"reviewCnt":8,
			"find_age":"40",
			"find_gender":"F",
			"reviewCnt":8,
			"nint_card_flag":"무이자6",
			"hash_list":["일자코트", "데님셔츠", "트렌치코트"]
		},{
			"isHimart": false,
			"brandNm": "[밀레(아웃도어)]",
			"saleRate": "17",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "200505916",
			"goodsCmpsCd": "30",
			"goodsNm": "밀레 다운 입고 춥지않고 따뜻하게 보내자!",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/16\/59\/50\/00\/2\/200505916_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 123670,
			"isTvhome": false,
			"price1": 149000,
			"_avg_gdas_stfd_val":"3.2",
			"_reviewCnt":24,
			"find_age":"20",
			"find_gender":"F"
		},{
			"isHimart": false,
			"brandNm": "[라푸마]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "177612063",
			"goodsCmpsCd": "50",
			"goodsNm": "[다운조끼 증정]남\/여 EVER(에버) FresHeat 구스다운 점퍼[LMJ05D867,LFJ05D867]",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/63\/20\/61\/77\/1\/177612063_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "12",
			"byrAgelmt": "0",
			"curDispNo": "235420319",
			"price2": 23235510,
			"isTvhome": false,
			"price1": 278600,
			"find_age":"30",
			"find_gender":"M"
		},{
			"isHimart": false,
			"brandNm": "",
			"saleRate": "0",
			"useCpn": "coupon",
			"outlnk": "http://m.lottesuper.co.kr/handler/goods/GoodsDetail?AFCR_TRK=Y&goods_no=1376035&CHL_NO=M384143",
			"goodsNo": "1376035",
			"goodsCmpsCd": "30",
			"goodsNm": "[롯데슈퍼] 쁘띠첼 미초 그린애플 900mlx3개",
			"isDept": false,
			"isYoung": false,
			"isSuper": true,
			"imgUrl": "http:\/\/image.lottesuper.co.kr\/35\/60\/37\/1\/1376035_1_200.jpg",
			"flag": [],
			"isSmpick": false,
			"outlnkMall": "SP",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "100040000800008",
			"price2": 30900,
			"isTvhome": false,
			"price1": 0,
			"outlnk":"http://m.lottesuper.co.kr/handler/goods/GoodsDetail?AFCR_TRK=Y&goods_no=1376035&CHL_NO=M384143",
			"outlnkMall":"SP"
		},{
			"isHimart": false,
			"brandNm": "[유니클로]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "UQ31084548",
			"goodsCmpsCd": "30",
			"goodsNm": "라이트롱가디건(긴팔)",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http://mimage.uniqlo.kr/goods/31/08/45/48/401670000_COL_COL11_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "UQ1A03A02A08",
			"price2": 169150,
			"isTvhome": false,
			"price1": 199000,
			"outlnk":"http://www.uniqlo.com/kr/ko/product/401670000?influx_channel_no=101617&influx_channel_detail_no=2994638&influx_channel_no=126324&influx_channel_detail_no=2772553",
			"outlnkMall":"LECS"
		},{
			"isHimart": false,
			"brandNm": "[코오롱스포츠]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "191645677",
			"goodsCmpsCd": "30",
			"goodsNm": "추운건 질색? 그러면 선택해! 코오롱 긴기장 다운모음!",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/77\/56\/64\/91\/1\/191645677_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420349",
			"price2": 311900,
			"isTvhome": false,
			"price1": 330000
		},{
			"isHimart": false,
			"brandNm": "[휠라(아웃도어)]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "185191131",
			"goodsCmpsCd": "30",
			"goodsNm": "다운\/자켓\/베스트\/티셔츠\/팬츠\/트레킹화 17종 택1",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/31\/11\/19\/85\/1\/185191131_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5419967",
			"price2": 67150,
			"isTvhome": false,
			"price1": 79000
		},{
			"isHimart": false,
			"brandNm": "[케이투]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "196791720",
			"goodsCmpsCd": "30",
			"goodsNm": "추위에 떨지않는 겨울을 위해! 겨울상품 모음!",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/20\/17\/79\/96\/1\/196791720_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 278050,
			"isTvhome": false,
			"price1": 329000
		},{
			"isHimart": false,
			"brandNm": "[빈폴아웃도어]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "201414883",
			"goodsCmpsCd": "30",
			"goodsNm": "[빈폴아웃도어]김수현이 추천하는 겨울인기 도브다운 20종 점퍼\/경량다운\/자켓\/도브다운",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/03\/19\/26\/99\/1\/199261903_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "EC",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5419059",
			"price2": 55860,
			"isTvhome": false,
			"price1": 58800
		},{
			"isHimart": false,
			"brandNm": "[디스커버리]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "199261903",
			"goodsCmpsCd": "30",
			"goodsNm": "[디스커버리]겨울아우터&자켓 8종 택1",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/03\/19\/26\/99\/1\/199261903_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5419967",
			"price2": 172400,
			"isTvhome": false,
			"price1": 204000
		},{
			"isHimart": false,
			"brandNm": "[아디다스 오리지날]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "192169626",
			"goodsCmpsCd": "50",
			"goodsNm": "배지&덕 다운 패딩파카(AC0506,AC0507,AH5751,AH5752,AH5753)",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/26\/96\/16\/92\/1\/192169626_9_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "2",
			"byrAgelmt": "0",
			"curDispNo": "5420067",
			"price2": 218950,
			"isTvhome": false,
			"price1": 259000
		},{
			"isHimart": false,
			"brandNm": "[휠라 아웃도어]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "98755246",
			"goodsCmpsCd": "50",
			"goodsNm": "(14년 상품) 남.여 코트형 롱다운점퍼 (O2DJW793.4) 양말+버프증정",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/46\/52\/75\/98\/98755246_12_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "25",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 84150,
			"isTvhome": false,
			"price1": 99000
		},{
			"isHimart": false,
			"brandNm": "[컬럼비아]",
			"saleRate": "17",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "190561746",
			"goodsCmpsCd": "50",
			"goodsNm": "2015 신상 방수 옴니테크, 보온성최상 옴니히트 야상스타일 다운자켓 CV4WE4120",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/46\/17\/56\/90\/1\/190561746_12_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "31",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 115370,
			"isTvhome": false,
			"price1": 139000
		},{
			"isHimart": false,
			"brandNm": "[노스페이스]",
			"saleRate": "20",
			"useCpn": "",
			"outlnk": "",
			"goodsNo": "186814909",
			"goodsCmpsCd": "50",
			"goodsNm": "남,여 스펙트럼 다운 자켓 [NFJ1DF58,NFJ1DF87] SPECTRUM DOWN JACKET",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/09\/49\/81\/86\/1\/186814909_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "26",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 234100,
			"isTvhome": false,
			"price1": 235200
		},{
			"isHimart": false,
			"brandNm": "[빈폴아웃도어]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "192579911",
			"goodsCmpsCd": "50",
			"goodsNm": "[사은품증정]15FW 인기상품 김수현다운 도브다운 6종 택1 BO5838018",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/11\/99\/57\/92\/1\/192579911_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "5",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 281700,
			"isTvhome": false,
			"price1": 298000
		},{
			"isHimart": false,
			"brandNm": "[블랙야크]",
			"saleRate": "17",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "32441726",
			"goodsCmpsCd": "50",
			"goodsNm": "15년 FW 신상품 라쿤퍼 L퍼지다운자켓#1",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/26\/17\/44\/32\/32441726_3_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "7",
			"byrAgelmt": "0",
			"curDispNo": "5419967",
			"price2": 198000,
			"isTvhome": false,
			"price1": 240000
		},{
			"isHimart": false,
			"brandNm": "[노스페이스 화이트라벨]",
			"saleRate": "0",
			"useCpn": "",
			"outlnk": "",
			"goodsNo": "191955184",
			"goodsCmpsCd": "50",
			"goodsNm": "남여 공용 등산 캐주얼 신소재 브이엑스 맥머도 파카 다운 자켓 NVJ3NG50",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/84\/51\/95\/91\/1\/191955184_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "3",
			"byrAgelmt": "0",
			"curDispNo": "5420067",
			"price2": 268700,
			"isTvhome": false,
			"price1": 270000
		},{
			"isHimart": false,
			"brandNm": "[노스페이스 화이트라벨]",
			"saleRate": "0",
			"useCpn": "",
			"outlnk": "",
			"goodsNo": "191954980",
			"goodsCmpsCd": "50",
			"goodsNm": "남성 등산 캐주얼 맥머도 15 다운 파카 기능성 구스 다운 패딩 자켓 NVJ1DG55",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/80\/49\/95\/91\/1\/191954980_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420067",
			"price2": 417900,
			"isTvhome": false,
			"price1": 420000
		},{
			"isHimart": false,
			"brandNm": "[네파 이젠벅]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "190048183",
			"goodsCmpsCd": "50",
			"goodsNm": "퀀볼 롱패딩 [BB80903]",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/83\/81\/04\/90\/1\/190048183_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "1",
			"byrAgelmt": "0",
			"curDispNo": "5420349",
			"price2": 94050,
			"isTvhome": false,
			"price1": 99000
		},{
			"isHimart": false,
			"brandNm": "[험멜]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "198861967",
			"goodsCmpsCd": "50",
			"goodsNm": "[험멜코리아] 다운 패딩 HM-W6997,HM-W6986,HM-W6999,HM-W6998,HM-6983",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/67\/19\/86\/98\/1\/198861967_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "EC",
			"reviewCnt": "1",
			"byrAgelmt": "0",
			"curDispNo": "5418800",
			"price2": 46550,
			"isTvhome": false,
			"price1": 49000
		},{
			"isHimart": false,
			"brandNm": "[빈폴아웃도어]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "183371246",
			"goodsCmpsCd": "50",
			"goodsNm": "15 FW 김수현다운 신상 도브다운 6종 택1 BO5838018",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/46\/12\/37\/83\/1\/183371246_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": true,
			"outlnkMall": "D",
			"reviewCnt": "13",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 281700,
			"isTvhome": false,
			"price1": 298000
		},{
			"isHimart": false,
			"brandNm": "[블랙야크]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "191937562",
			"goodsCmpsCd": "30",
			"goodsNm": "추운겨울 NO 블랙야크로 따뜻하게! 인기다운 택1",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/62\/75\/93\/91\/1\/191937562_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420319",
			"price2": 211300,
			"isTvhome": false,
			"price1": 250000
		},{
			"isHimart": false,
			"brandNm": "[데상트(의류)]",
			"saleRate": "5",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "183345717",
			"goodsCmpsCd": "50",
			"goodsNm": "데상트 트레이닝 덕다운 점퍼 남녀공용  [S5423TDJ10]",
			"isDept": false,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/17\/57\/34\/83\/1\/183345717_1_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "EC",
			"reviewCnt": "12",
			"byrAgelmt": "0",
			"curDispNo": "5418800",
			"price2": 263750,
			"isTvhome": false,
			"price1": 279000
		},{
			"isHimart": false,
			"brandNm": "[아디다스 오리지날]",
			"saleRate": "15",
			"useCpn": "coupon",
			"outlnk": "",
			"goodsNo": "194625385",
			"goodsCmpsCd": "30",
			"goodsNm": "따뜻한 겨울을 보낼수있는 다운 파카 최고 20% 할인이벤트!",
			"isDept": true,
			"isYoung": false,
			"isSuper": false,
			"imgUrl": "http:\/\/image.lotte.com\/goods\/85\/53\/62\/94\/1\/194625385_9_280.jpg",
			"flag": ["무료배송"],
			"isSmpick": false,
			"outlnkMall": "D",
			"reviewCnt": "0",
			"byrAgelmt": "0",
			"curDispNo": "5420066",
			"price2": 41650,
			"isTvhome": false,
			"price1": 49000
		}],
		"tcnt": 30
   }
   <% } %>
   <% if(isModify){ %>
   ,"missKeyword":{"orgKeyword":"우너피스"}
   <% } %>
   ,"_planPrdLst": {
        "items": [{
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "5",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "198",
            "isHimart": false,
            "brandNm": "[프랜치캣]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "163223116",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "11111 사랑스러움 UP! 여아 추천코디★",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/16\/31\/22\/63\/1\/163223116_0.jpg",
            "flag": [],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5408176",
            "isTvhome": false,
            "price2": 10550,
            "isDlvQuick": false,
            "price1": 11100
        }],
        "tcnt": 1
    }
   ,"planPrdLst": {
        "items": [{
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "5",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "198",
            "isHimart": false,
            "brandNm": "[프랜치캣]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "163223116",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "사랑스러움 UP! 여아 추천코디★",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/16\/31\/22\/63\/1\/163223116_0.jpg",
            "flag": [],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5408176",
            "isTvhome": false,
            "price2": 10550,
            "isDlvQuick": false,
            "price1": 11100
            },{
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "5",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "198",
            "isHimart": false,
            "brandNm": "[프랜치캣]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "163223116",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "사랑스러움 UP! 여아 추천코디★",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/16\/31\/22\/63\/1\/163223116_0.jpg",
            "flag": [],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5408176",
            "isTvhome": false,
            "price2": 10550,
            "isDlvQuick": false,
            "price1": 11100
        }, {
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "10",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "isSmpick": false,
            "isSuper": false,
            "reviewCnt": "213",
            "isHimart": false,
            "brandNm": "[이앤씨]",
            "vodUrl": "",
            "isCrsPickYn": false,
            "isHoliday": false,
            "goodsNo": "452261814",
            "isYoung": false,
            "isDept": false,
            "goodsNm": "[이앤씨 본사특가] EnC와 함께하는 WINTER 페스티벌~!",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/14\/18\/26\/52\/4\/452261814_0.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "EC",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5414689",
            "isTvhome": false,
            "price2": 89100,
            "isDlvQuick": false,
            "price1": 99000
        }, {
            "find_age": "30",
            "avg_gdas_stfd_val": "4.7",
            "saleRate": "10",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": false,
            "isSuper": false,
            "reviewCnt": "203",
            "isHimart": false,
            "brandNm": "[이앤씨]",
            "vodUrl": "",
            "isCrsPickYn": false,
            "isHoliday": false,
            "goodsNo": "444500674",
            "isYoung": false,
            "isDept": false,
            "goodsNm": "[이앤씨EnC][본사 단독특가] 여기, 지금, 우리, EnC특가상품! 70%~",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/74\/06\/50\/44\/4\/444500674_0.jpg",
            "flag": [],
            "outlnkMall": "EC",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5414681",
            "isTvhome": false,
            "price2": 44100,
            "isDlvQuick": false,
            "price1": 49000
        }, {
            "find_age": "30",
            "avg_gdas_stfd_val": "4.7",
            "saleRate": "17",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": false,
            "isSuper": false,
            "reviewCnt": "98",
            "isHimart": false,
            "brandNm": "[닥스 키즈]",
            "vodUrl": "",
            "isCrsPickYn": false,
            "isHoliday": false,
            "goodsNo": "469328902",
            "isYoung": false,
            "isDept": false,
            "goodsNm": "[닥스키즈]그뤠잇 패딩\/티\/팬츠\/원피스",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/02\/89\/32\/69\/4\/469328902_1_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "EC",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5409075",
            "isTvhome": false,
            "price2": 58770,
            "isDlvQuick": false,
            "price1": 70800
        }, {
            "find_age": "30",
            "avg_gdas_stfd_val": "4.5",
            "saleRate": "10",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": false,
            "isSuper": false,
            "reviewCnt": "70",
            "isHimart": false,
            "brandNm": "[이앤씨]",
            "vodUrl": "",
            "isCrsPickYn": false,
            "isHoliday": false,
            "goodsNo": "467341861",
            "isYoung": false,
            "isDept": false,
            "goodsNm": "[EnC본사단독] 어서와, 봄신상품 특가로 준비해~! 70%",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/61\/18\/34\/67\/4\/467341861_0.jpg",
            "flag": [],
            "outlnkMall": "EC",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5414679",
            "isTvhome": false,
            "price2": 44100,
            "isDlvQuick": false,
            "price1": 49000
        }, {
            "find_age": "20",
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "15",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "127",
            "isHimart": false,
            "brandNm": "[제이제이 지고트]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": false,
            "goodsNo": "475949107",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "롯데단독특가★2018' 봄데일룩의 정석! 신상+BEST 원피스\/코트外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/07\/91\/94\/75\/4\/475949107_0.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416186",
            "isTvhome": false,
            "price2": 41650,
            "isDlvQuick": false,
            "price1": 49000
        }, {
            "avg_gdas_stfd_val": "4.5",
            "saleRate": "20",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "152",
            "isHimart": false,
            "brandNm": "[보브(의류)]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "469573175",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "롯데단독★깜짝 놀랄만한 품목SALE★ 여성 롱코트\/니트\/원피스外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/75\/31\/57\/69\/4\/469573175_4_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": true,
            "curDispNo": "5416933",
            "isTvhome": false,
            "price2": 111200,
            "isDlvQuick": false,
            "price1": 139000
        }, {
            "find_age": "20",
            "avg_gdas_stfd_val": "4.6",
            "saleRate": "13",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "257",
            "isHimart": false,
            "brandNm": "[잇미샤]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "474907558",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "단독! 셀럽들만 입는 2018'S 최초공개★최대 58%OFF 여성코트\/원피스外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/58\/75\/90\/74\/4\/474907558_1_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": true,
            "curDispNo": "5416933",
            "isTvhome": false,
            "price2": 50730,
            "isDlvQuick": false,
            "price1": 58310
        }, {
            "find_age": "30",
            "avg_gdas_stfd_val": "4.7",
            "saleRate": "13",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "210",
            "isHimart": false,
            "brandNm": "[잇미샤]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": false,
            "goodsNo": "436351675",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "로맨틱 겨울~ BEST ITEM만 모았다! 코트\/원피스\/블라우스 外",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/75\/16\/35\/36\/4\/436351675_4_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416933",
            "isTvhome": false,
            "price2": 127470,
            "isDlvQuick": false,
            "price1": 146510
        }, {
            "find_age": "20",
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "10",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "133",
            "isHimart": false,
            "brandNm": "[제이제이 지고트]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": false,
            "goodsNo": "446351974",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "슈퍼 그뤠잇한 겨울부터 봄까지 간절기 신상 大공개★롯데단독가 여성자켓\/원피스外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/74\/19\/35\/46\/4\/446351974_0.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416933",
            "isTvhome": false,
            "price2": 31500,
            "isDlvQuick": false,
            "price1": 35000
        }, {
            "find_age": "20",
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "5",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "188",
            "isHimart": false,
            "brandNm": "[숲(SOUP)]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": false,
            "goodsNo": "426453228",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "지금부터 입기 딱 좋은 니트원피스外 하객원피스 여성스럽게 코디해봐~!",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/28\/32\/45\/26\/4\/426453228_1_280.jpg",
            "flag": [],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416241",
            "isTvhome": false,
            "price2": 27550,
            "isDlvQuick": false,
            "price1": 29000
        }, {
            "find_age": "30",
            "avg_gdas_stfd_val": "4.5",
            "saleRate": "14.5",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": false,
            "find_gender": "F",
            "isSmpick": false,
            "isSuper": false,
            "reviewCnt": "76",
            "isHimart": false,
            "brandNm": "[이앤씨]",
            "vodUrl": "",
            "isCrsPickYn": false,
            "isHoliday": false,
            "goodsNo": "470075660",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "★단독특가★지금부터 봄까지! 반응 좋은 인기BEST 여성 가디건\/니트外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/60\/56\/07\/70\/4\/470075660_3_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416301",
            "isTvhome": false,
            "price2": 29900,
            "isDlvQuick": false,
            "price1": 35000
        }, {
            "find_age": "40",
            "avg_gdas_stfd_val": "4.9",
            "saleRate": "15",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "find_gender": "F",
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "8",
            "isHimart": false,
            "brandNm": "[세컨플로어]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "450921674",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "반응최고! SEASON OFF 깜짝 50% 할인에 봄 상품까지?! 아우터\/원피스\/블라우스外 택1",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/74\/16\/92\/50\/4\/450921674_4_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": true,
            "curDispNo": "5416161",
            "isTvhome": false,
            "price2": 74380,
            "isDlvQuick": false,
            "price1": 87500
        }, {
            "avg_gdas_stfd_val": "4.8",
            "saleRate": "15",
            "useCpn": "coupon",
            "nint_card_flag": "",
            "outlnk": "",
            "isDlvToday": false,
            "goodsCmpsCd": "30",
            "isGiftPkg": true,
            "isSmpick": true,
            "isSuper": false,
            "reviewCnt": "44",
            "isHimart": false,
            "brandNm": "[앳코너]",
            "vodUrl": "",
            "isCrsPickYn": true,
            "isHoliday": true,
            "goodsNo": "460793318",
            "isYoung": false,
            "isDept": true,
            "goodsNm": "겨울을 즐길 줄 아는 너! 바로 패셔니스타! 이쁜아우터 골라봐~ 패딩\/코트\/원피스外",
            "savePoint": "0",
            "imgUrl": "http:\/\/image.lotte.com\/goods\/18\/33\/79\/60\/4\/460793318_2_280.jpg",
            "flag": ["무료배송"],
            "outlnkMall": "D",
            "byrAgelmt": "0",
            "isDeptPickYn": false,
            "curDispNo": "5416666",
            "isTvhome": false,
            "price2": 84150,
            "isDlvQuick": false,
            "price1": 99000
        }],
        "tcnt": 14
    }
}
<%
// 검색결과 있는 경우 끝
}else{
// 검색결과 없는 경우
%>
{
	"resultCode":"1000",
	<%
	if(redirectUrl){
	// 키워드 URL 포워딩
	%>
	"isVoice": "Y",
	"redirectUrl":"/mylotte/m/mylotte_dev.html",
	<%
	}else{
	// 음성검색
	%>
	"isVoice": "N",
	"redirectUrl":"",
	<%
	}
	// 일반 검색
	%>
	"dispCnt":"30",
	"tCnt":0,
	"ageGndrGrpLst":{},
	"prdLst":{},
	"prdDealLst":{},
	"missKeyword":{"cnt":"0","keyword":""},
	<%
	//스마트픽 검색 실패 시 배너 코너화
	if(keyword.indexOf("스마트픽") >= 0){
	%>
	"smpBanner":{
		"imgUrl"	: "http://image.lotte.com/lotte/images/search/smartpick/20170906_search_bn.png",
		"linkUrl"	: "http://m.lotte.com/product/m/product_list.do?curDispNo=5409473"
	},
	<% } %>
	"favLst":{
		"items":[{
			"rank":"NEW",
			"keyword":"스킨푸드"
		},{
			"rank":"NEW",
			"keyword":"bnx"
		},{
			"rank":"NEW",
			"keyword":"접시"
		},{
			"rank":"NEW",
			"keyword":"si"
		},{
			"rank":"60",
			"keyword":"무스탕"
		},{
			"rank":"NEW",
			"keyword":"게스청바지"
		},{
			"rank":"NEW",
			"keyword":"겔랑"
		},{
			"rank":"NEW",
			"keyword":"오설록"
		},{
			"rank":"57",
			"keyword":"크로스백"
		},{
			"rank":"NEW",
			"keyword":"트레이닝복세트"
		}],
		"date":"20160115110803"
	}
}
<%
// 검색결과 없는 경우 끝
}
%>