document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/common/lotte.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/header.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/header_sub.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/footer.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/actionbar.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/side_ctg.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/layout/side_mylotte.css"/>');
document.write('<link rel="stylesheet" type="text/css" href="/lotte/resources_dev/search/layer_srh.css"/>');

document.write('<script src="/lotte/lib/jquery/jquery-1.11.2.min.js"></script>');
document.write('<script src="/lotte/lib/jquery/cnt_interface.js"></script>');
document.write('<script src="/lotte/lib/jquery/app_interface.js"></script>');
document.write('<script src="/lotte/lib/angular/angular.min.js"></script>');
document.write('<script src="/lotte/lib/angular/angular-sanitize.min.js"></script>');
document.write('<script src="/lotte/lib/angular/angular-touch.min.js"></script>');
document.write('<script src="/lotte/lib/angular/angular-carousel.min.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_comm.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_util.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_filter.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_svc_dev.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_search.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_comm_footer.js"></script>');
document.write('<script src="/lotte/resources_dev/common/lotte_log.js"></script>');
document.write('<script src="/lotte/resources_dev/layout/lotte_sidectg.js"></script>');
document.write('<script src="/lotte/resources_dev/layout/lotte_sidemylotte.js"></script>');