//Release: 17
//BUILD 46
function CrittercismClass(){function x(a){this.isValidAppId=!1;if(null!==a.match(/^[a-f0-9]{24,40}$/gi)){if(24===a.length)a="crittercism.com";else if(40===a.length)switch(a=a.substring(32),a){case "00555300":a="crittercism.com";break;case "00555304":a="crit-ci.com";break;case "00555305":a="crit-staging.com";break;case "00444503":a="de.crittercism.com";break;default:return}else return;this.isValidAppId=!0;this.configuredApiUrl="https://api."+a;this.configuredApmUrl="https://apm."+a;this.configuredTxnUrl=
"https://txn.ingest."+a}}function y(a){var b=window.localStorage.getItem(a)||"[]";this.previous_session=JSON.parse(b);this.current_session=[];this.leaveBreadcrumb=function(b){if("string"!==typeof b)throw Error("Invalid breadcrumb type; must be a string");b=b.substr(0,140);100<=this.current_session.length&&this.current_session.splice(1,1);this.current_session.push([b,B()]);window.localStorage.setItem(a,JSON.stringify(this.current_session))};this.leaveBreadcrumb("session_start")}function s(a,b){var d=
1,c=new Date;this.tryEvent=function(){var f=new Date,e=f-c;c=f;d+=a/b*e;d>a&&(d=a);return 1<=d?(d-=1,!0):!1}}function z(a,b){function d(a){b||window.console.log(a)}this.app_id=a;this.metadata={};this.setMetadata=function(a){var b,e=!1;if("object"!==typeof a)return d("Crittercism setMetadata given a parameter that is not an object: "+a),!1;this.metadata.username&&!a.username&&(a.username=this.metadata.username);for(b in this.metadata)a.hasOwnProperty(b)||(delete this.metadata[b],e=!0);for(b in a)a.hasOwnProperty(b)&&
this.setValue(b,a[b])&&(e=!0);return e};this.setValue=function(a,b){var e=!1;if("string"!==typeof a)return d("Crittercism setValue given a key that is not a string: "+a),!1;if("string"!==typeof b&&"number"!==typeof b)return d("Crittercism setValue given a value that is not a string or a number"+b),!1;e=this.metadata[a]!==b;this.metadata[a]=b;return e};this.getValue=function(a){return"string"!==typeof a?(d("Crittercism getValue given a key that is not a string: "+a),null):this.metadata[a]};this.setUsername=
function(a){return"string"!==typeof a?(d("Crittercism setUsername given a name that is not a string: "+a),!1):this.setValue("username",a)};this.getUsername=function(){return this.getValue("username")}}function C(){var a,b;b=(a=window.localStorage.getItem("Crittercism.last_seen"))?new Date(a):null;return b?(a=new Date,18E5<=a-b):!0}function h(){window.localStorage.setItem("Crittercism.last_seen",(new Date).toString())}function q(a,b,d){if(a&&b){var c=!1;if(window.XMLHttpRequest)c=new XMLHttpRequest,
c.overrideMimeType&&c.overrideMimeType(d);else if(window.ActiveXObject)try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(f){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){}}if(!c)return!1;c.open("POST",a,!0);c.withCredentials=!0;c.setRequestHeader("Content-type",d);c.send(b)}}function l(a){a=a||{guess:!0};var b=a.e||null;a=!!a.guess;var d=new l.implementation,b=d.run(b);return a?d.guessAnonymousFunctions(b):b}function t(a){for(var b=[],d=[/^crittercismErrorHandler/i,/^printStackTrace/i],c=0,
f=a.length;c<f;c++){for(var e=a[c],g=!1,k=0,h=d.length;k<h;k++)if(e.match(d[k])){g=!0;break}g||b.push(e)}return b}function D(){var a=JSON.stringify({app_id:n,library_version:"2.2",app_state:{app_version:r}});q(p+"/app_loads",a,"application/json;charset=UTF-8")}function u(){E.tryEvent()&&q(p+"/metadata",JSON.stringify(m),"application/json;charset=UTF-8")}function B(){function a(a){return 10>a?"0"+a:a}var b=new Date;return b.getUTCFullYear()+"-"+a(b.getUTCMonth()+1)+"-"+a(b.getUTCDate())+"T"+a(b.getUTCHours())+
":"+a(b.getUTCMinutes())+":"+a(b.getUTCSeconds())+"Z"}function F(a){if(A.tryEvent()){var b=a&&"string"==typeof a.name?a.name:"Unknown Exception (No name passed by caller)",d=a&&"string"==typeof a.message?a.message:"Unknown Exception Reason (No reason passed by caller)";a=a&&a.stack?t(l({e:a,guess:!0})):t(l({e:d,guess:!0}));q(p+"/errors",JSON.stringify({app_id:n,library_version:"2.2",exceptions:[{library_version:"2.2",exception_name:b,exception_reason:d,breadcrumbs:v,state:{app_version:r},unsymbolized_stacktrace:a}]}),
"application/json;charset=UTF-8");return this}}var E=new s(5,6E4),A=new s(5,6E4),n=null,k=!1,p=null,r,w=null,m,v=new y("Crittercism.breadcrumbs");l.implementation=function(){};l.implementation.prototype={run:function(a,b){a=a||this.createException();b=b||this.mode(a);return"other"===b?this.other(arguments.callee):this[b](a)},createException:function(){try{this.undef()}catch(a){return a}},mode:function(a){return a.arguments&&a.stack?"chrome":"string"===typeof a.message&&"undefined"!==typeof window&&
window.opera?!a.stacktrace||-1<a.message.indexOf("\n")&&a.message.split("\n").length>a.stacktrace.split("\n").length?"opera9":a.stack?0>a.stacktrace.indexOf("called from line")?"opera10b":"opera11":"opera10a":a.stack?"firefox":"other"},instrumentFunction:function(a,b,d){a=a||window;var c=a[b];a[b]=function(){d.call(this,l().slice(4));return a[b]._instrumented.apply(this,arguments)};a[b]._instrumented=c},deinstrumentFunction:function(a,b){a[b].constructor===Function&&a[b]._instrumented&&a[b]._instrumented.constructor===
Function&&(a[b]=a[b]._instrumented)},chrome:function(a){a=(a.stack+"\n").replace(/^\S[^\(]+?[\n$]/gm,"").replace(/^\s+(at eval )?at\s+/gm,"").replace(/^([^\(]+?)([\n$])/gm,"{anonymous}()@$1$2").replace(/^Object.<anonymous>\s*\(([^\)]+)\)/gm,"{anonymous}()@$1").split("\n");a.pop();return a},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,"").replace(/^\(/gm,"{anonymous}(").split("\n")},opera11:function(a){var b=/^.*line (\d+), column (\d+)(?: in (.+))? in (\S+):$/;a=a.stacktrace.split("\n");
for(var d=[],c=0,f=a.length;c<f;c+=2){var e=b.exec(a[c]);if(e){var g=e[4]+":"+e[1]+":"+e[2],e=e[3]||"global code",e=e.replace(/<anonymous function: (\S+)>/,"$1").replace(/<anonymous function>/,"{anonymous}");d.push(e+"@"+g+" -- "+a[c+1].replace(/^\s+/,""))}}return d},opera10b:function(a){var b=/^(.*)@(.+):(\d+)$/;a=a.stacktrace.split("\n");for(var d=[],c=0,f=a.length;c<f;c++){var e=b.exec(a[c]);e&&d.push((e[1]?e[1]+"()":"global code")+"@"+e[2]+":"+e[3])}return d},opera10a:function(a){var b=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;
a=a.stacktrace.split("\n");for(var d=[],c=0,f=a.length;c<f;c+=2){var e=b.exec(a[c]);e&&d.push((e[3]||"{anonymous}")+"()@"+e[2]+":"+e[1]+" -- "+a[c+1].replace(/^\s+/,""))}return d},opera9:function(a){var b=/Line (\d+).*script (?:in )?(\S+)/i;a=a.message.split("\n");for(var d=[],c=2,f=a.length;c<f;c+=2){var e=b.exec(a[c]);e&&d.push("{anonymous}()@"+e[2]+":"+e[1]+" -- "+a[c+1].replace(/^\s+/,""))}return d},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,d=[],c,f;a&&a.arguments&&10>d.length;)c=
b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",f=Array.prototype.slice.call(a.arguments||[]),d[d.length]=c+"("+this.stringifyArguments(f)+")",a=a.caller;return d},stringifyArguments:function(a){for(var b=[],d=Array.prototype.slice,c=0;c<a.length;++c){var f=a[c];void 0===f?b[c]="undefined":null===f?b[c]="null":f.constructor&&(f.constructor===Array?b[c]=3>f.length?"["+this.stringifyArguments(f)+"]":"["+this.stringifyArguments(d.call(f,0,1))+"..."+this.stringifyArguments(d.call(f,-1))+"]":
f.constructor===Object?b[c]="#object":f.constructor===Function?b[c]="#function":f.constructor===String?b[c]='"'+f+'"':f.constructor===Number&&(b[c]=f))}return b.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();if(b)try{return b.open("GET",a,!1),b.send(null),b.responseText}catch(d){}return""},createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},
function(){return new ActiveXObject("Microsoft.XMLHTTP")}],d=0;d<b.length;d++)try{return a=b[d](),this.createXMLHTTPObject=b[d],a}catch(c){}},isSameDomain:function(a){return"undefined"!==typeof location&&-1!==a.indexOf(location.hostname)},getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));return this.sourceCache[a]},guessAnonymousFunctions:function(a){for(var b=0;b<a.length;++b){var d=/^(.*?)(?::(\d+))(?::(\d+))?(?: -- .+)?$/,c=a[b],f=/\{anonymous\}\(.*\)@(.*)/.exec(c);
if(f){var e=d.exec(f[1]);e&&(d=e[1],f=e[2],e=e[3]||0,d&&this.isSameDomain(d)&&f&&(d=this.guessAnonymousFunction(d,f,e),a[b]=c.replace("{anonymous}",d)))}}return a},guessAnonymousFunction:function(a,b,d){var c;try{c=this.findFunctionName(this.getSource(a),b)}catch(f){c="getSource failed with url: "+a+", exception: "+f.toString()}return c},findFunctionName:function(a,b){for(var d=/function\s+([^(]*?)\s*\(([^)]*)\)/,c=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*function\b/,f=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*(?:eval|new Function)\b/,
e="",g,k=Math.min(b,20),h,l=0;l<k;++l)if(g=a[b-l-1],h=g.indexOf("//"),0<=h&&(g=g.substr(0,h)),g)if(e=g+e,(g=c.exec(e))&&g[1]||(g=d.exec(e))&&g[1]||(g=f.exec(e))&&g[1])return g[1];return"(?)"}};this.init=function(a){var b;try{window.localStorage.setItem("CRITTERCISM_LOCAL_STORAGE_TEST","1"),window.localStorage.removeItem("CRITTERCISM_LOCAL_STORAGE_TEST"),b=!0}catch(d){b=!1}if(b)if(k)console.log("Calling Crittercism.init(), but Crittercism is already initialized");else{var c=window.onerror;window.onerror=
function(a,b,d,k,h){if(A.tryEvent()){var m=t(l({e:h||a,guess:!0}));q(p+"/crashes",JSON.stringify({app_id:n,app_state:{app_version:r},breadcrumbs:v,exception_name:"Error",exception_reason:a,library_version:"2.2",unsymbolized_stacktrace:m}),"application/json;charset=UTF-8")}c&&c(a,b,d,k,h)};k=!0;n=a.appId;m=new z(n);r=a.appVersion||"unspecified";w=new x(n);if(w.isValidAppId)p=w.configuredApiUrl;else throw Error("Crittercism is disabled because appId '"+n+"' is invalid");(C()||a._critterSendAppLoad)&&
D();h();return this}else console.log("Crittercism is disabled because local storage is not available")};this.setMetadata=function(a){if(!k)throw Error("Crittercism.init call required before setMetadata");m.setMetadata(a)&&u();h();return this};this.setValue=function(a,b){if(!k)throw Error("Crittercism.init call required before setValue");m.setValue(a,b)&&u();h();return this};this.getValue=function(a){if(!k)throw Error("Crittercism.init call required before getValue");h();return m.getValue(a)};this.setUsername=
function(a){if(!k)throw Error("Crittercism.init call required before setUsername");m.setUsername(a)&&u();h();return this};this.getUsername=function(){if(!k)throw Error("Crittercism.init call required before getUsername");h();return m.getUsername()};this.logHandledException=function(a){if(!k)throw Error("Crittercism.init call required before logHandledException");F(a);h();return this};this.leaveBreadcrumb=function(a){if(!k)throw Error("Crittercism.init call required before leaveBreadcrumb");v.leaveBreadcrumb(a);
h();return this};this.AppLocator=x;this.Throttle=s;this.Breadcrumbs=y;this.Metadata=z}Crittercism=new CrittercismClass;
