//Release: 18
//BUILD 50
function CrittercismClass(){function A(a){function b(a){return"string"==typeof a?a:a instanceof String?a.toString():null}this.sendHandledException=function(a,d,g){if("undefined"!=typeof _crttr){a=b(a);d=b(d);var e=null;"object"==typeof g&&(e=g.join("\r\n"));_crttr.logHandledException(a,d,e)}};this.sendUnhandledException=function(a,d,g){"undefined"!=typeof _crttr&&(a=b(a),d=b(d),g=null,"object"==typeof stack&&(g=stack.join("\r\n")),_crttr.logUnhandledException(a,d,g))};this.logNetworkRequest=function(a,
d,g,e,f,h,n){"undefined"!=typeof _crttr&&(a=b(a),d=b(d),g=parseInt(g),e=parseInt(e),f=parseInt(f),h=parseInt(h),n=parseInt(n),_crttr.logNetworkRequest(a,d,g,e,f,h,n))};this.leaveBreadcrumb=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.leaveBreadcrumb(a))};this.setMetadata=function(a){"undefined"!=typeof _crttr&&"object"==typeof a&&_crttr.setMetadata(JSON.stringify(a))};this.setUsername=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.setUsername(a))};this.setValue=function(a,d){if("undefined"!=
typeof _crttr){b(a);var g=b(d);_crttr.setMetadata(JSON.stringify({keyStr:g}))}};this.beginTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.beginTransaction(a))};this.endTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.endTransaction(a))};this.failTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.failTransaction(a))};this.setTransactionValue=function(a,d){if("undefined"!=typeof _crttr){var g=parseInt(d),e=b(a);g&&_crttr.setTransactionValue(e,g)}};
this.getTransactionValue=function(a){return"undefined"!=typeof _crttr?(a=b(a),_crttr.getTransactionValue(a)):-1}}function B(a){function b(a){a=JSON.stringify(a);c.src="com.crittercism://eval/"+encodeURIComponent(a)}var c=document.createElement("iframe");c.style.display="none";document.documentElement.appendChild(c);this.sendHandledException=function(a,c,e){e=e.join("\n");b(["logHandledException",a,c,e,2])};this.sendUnhandledException=function(a,c,e){e=e.join("\n");b(["logUnhandledException",a,c,e,
2])};this.logNetworkRequest=function(a,c,e,f,h,n,k){b(["logNetworkRequest",a,c,.001*e,f,h,n,k])};this.leaveBreadcrumb=function(a){b(["leaveBreadcrumb",a])};this.setUsername=function(a){b(["setUsername",a])};this.setValue=function(a,c){b(["setValue",c,a])};this.setMetadata=function(a){};this.beginTransaction=function(a){b(["beginTransaction",a])};this.endTransaction=function(a){b(["endTransaction",a])};this.failTransaction=function(a){b(["failTransaction",a])};this.setTransactionValue=function(a,c){b(["setTransactionValue",
a,c])};this.getTransactionValue=function(a){return-1}}function r(a){function b(a){this.isValidAppId=!1;if(a&&null!==a.match(/^[a-f0-9]{24,40}$/gi)){if(24===a.length)a="crittercism.com";else if(40===a.length)switch(a=a.substring(32),a){case "00555300":a="crittercism.com";break;case "00555304":a="crit-ci.com";break;case "00555305":a="crit-staging.com";break;case "00444503":a="de.crittercism.com";break;default:return}else return;this.isValidAppId=!0;this.configuredApiUrl="https://api."+a;this.configuredApmUrl=
"https://apm."+a;this.configuredTxnUrl="https://txn.ingest."+a}else f("Not a valid Crittercism appId == "+a)}function c(){var a=n("breadcrumbJson");a||(a="[]");this.previous_session=JSON.parse(a);this.current_session=[];this.leaveBreadcrumb=function(a){if("string"!=typeof a)throw Error("Invalid breadcrumb type; must be a string");a=a.substr(0,140);100<=this.current_session.length&&this.current_session.splice(1,1);this.current_session.push([a,g()]);a=JSON.stringify(this.current_session);try{localStorage.setItem(h("breadcrumbJson"),
a)}catch(b){}};this.leaveBreadcrumb("session_start")}function d(a,b){var c=1,d=new Date;this.tryEvent=function(){var e=new Date,g=e-d;d=e;c+=a/b*g;c>a&&(c=a);return 1<=c?(c-=1,!0):!1}}function g(){function a(b){return 10>b?"0"+b:b}var b=new Date;return b.getUTCFullYear()+"-"+a(b.getUTCMonth()+1)+"-"+a(b.getUTCDate())+"T"+a(b.getUTCHours())+":"+a(b.getUTCMinutes())+":"+a(b.getUTCSeconds())+"Z"}function e(){var a=(new Date).toString();try{localStorage.setItem(h("lastSeen"),a)}catch(b){}}function v(a,
b,c){if(a&&b){var d=!1;if(window.XMLHttpRequest)d=new XMLHttpRequest,d.overrideMimeType&&d.overrideMimeType(c);else if(window.ActiveXObject)try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(g){}}if(!d)return!1;d.open("POST",a,!0);d.withCredentials=!0;d.setRequestHeader("Content-type",c);d.send(b)}}function h(a){return"com.crittercism.html5/"+m+"/"+a}function n(a){var b=null;try{b=localStorage.getItem(h(a))}catch(c){}return b}function k(){if(r.tryEvent()){var a=
JSON.stringify(p);v(s+"/metadata",a,"application/json;charset=UTF-8")}}var l=null,q=null,s=null,t=null,r=new d(5,6E4),u=new d(5,6E4);this.getBreadcrumbs=function(){return t};this.AppLocator=b;this.Breadcrumbs=c;this.Throttle=d;this.sendHandledException=function(a,b,c){u.tryEvent()&&(v(s+"/errors",JSON.stringify({app_id:m,library_version:"2.3",exceptions:[{library_version:"2.3",exception_name:a,exception_reason:b,breadcrumbs:t,state:{app_version:l},unsymbolized_stacktrace:c}]}),"application/json;charset=UTF-8"),
e())};this.sendUnhandledException=function(a,b,c){e()};this.logNetworkRequest=function(a,b,c,d,g,f,h){e()};this.leaveBreadcrumb=function(a){t.leaveBreadcrumb(a);e()};this.setUsername=function(a){k();e()};this.setValue=function(a,b){k();e()};this.setMetadata=function(a){k();e()};this.beginTransaction=function(a){e()};this.endTransaction=function(a){e()};this.failTransaction=function(a){e()};this.setTransactionValue=function(a,b){e()};this.getTransactionValue=function(a){e();return-1};(function(a){l=
a.appVersion||"unspecified";q=new b(m);if(q.isValidAppId)s=q.configuredApiUrl;else throw Error("Crittercism is disabled because appId '"+m+"' is invalid");t=new c;var d;var g;d=null;(g=n("lastSeen"))&&(d=new Date(g));(g=d)?(d=new Date,d=18E5<=d-g):d=!0;if(d||a.appLoad)f("sendAppLoad"),a=JSON.stringify({app_id:m,library_version:"2.3",app_state:{app_version:l}}),v(s+"/app_loads",a,"application/json;charset=UTF-8");e()})(a)}function l(a){a=a||{guess:!0};var b=a.e||null;a=!!a.guess;var c=new l.implementation,
b=c.run(b);return a?c.guessAnonymousFunctions(b):b}function u(a){for(var b=[],c=[/^crittercismErrorHandler/i,/^printStackTrace/i],d=0,g=a.length;d<g;d++){for(var e=a[d],f=!1,h=0,k=c.length;h<k;h++)if(e.match(c[h])){f=!0;break}f||b.push(e)}return b}function f(a){w&&window.console.log("Crittercism: "+a)}function x(a){this.app_id=a;this.metadata={};this.setMetadata=function(a){var c,d=!1;if("object"!=typeof a)return f("Crittercism setMetadata given a parameter that is not an object: "+a),!1;this.metadata.username&&
!a.username&&(a.username=this.metadata.username);for(c in this.metadata)a.hasOwnProperty(c)||(delete this.metadata[c],d=!0);for(c in a)a.hasOwnProperty(c)&&this.setValue(c,a[c])&&(d=!0);return d};this.setValue=function(a,c){if("string"!=typeof a)return f("Crittercism setValue given a key that is not a string: "+a),!1;if("string"!=typeof c&&"number"!=typeof c)return f("Crittercism setValue given a value that is not a string or a number: "+c),!1;var d=this.metadata[a]!==c;this.metadata[a]=c;return d};
this.getValue=function(a){return"string"!=typeof a?(f("Crittercism getValue given a key that is not a string: "+a),null):this.metadata[a]};this.setUsername=function(a){return"string"!=typeof a?(f("Crittercism setUsername given a name that is not a string: "+a),!1):this.setValue("username",a)};this.getUsername=function(){return this.getValue("username")}}function y(a,b,c){f("sendHandledException");if(k)for(var d in h)h[d].sendHandledException(a,b,c);else f("Crittercism isn't initialized yet.  Can't sendHandledException.")}
var m=null,k=!1,w=!1,p,h={};this.getObserver=function(a){return h[a]};this.getObservers=function(){return h};this.Html5Observer=r;l.implementation=function(){};l.implementation.prototype={run:function(a,b){a=a||this.createException();b=b||this.mode(a);return"other"===b?this.other(arguments.callee):this[b](a)},createException:function(){try{this.undef()}catch(a){return a}},mode:function(a){return a.arguments&&a.stack?"chrome":"string"===typeof a.message&&"undefined"!==typeof window&&window.opera?!a.stacktrace||
-1<a.message.indexOf("\n")&&a.message.split("\n").length>a.stacktrace.split("\n").length?"opera9":a.stack?0>a.stacktrace.indexOf("called from line")?"opera10b":"opera11":"opera10a":a.stack?"firefox":"other"},instrumentFunction:function(a,b,c){a=a||window;var d=a[b];a[b]=function(){c.call(this,l().slice(4));return a[b]._instrumented.apply(this,arguments)};a[b]._instrumented=d},deinstrumentFunction:function(a,b){a[b].constructor===Function&&a[b]._instrumented&&a[b]._instrumented.constructor===Function&&
(a[b]=a[b]._instrumented)},chrome:function(a){a=(a.stack+"\n").replace(/^\S[^\(]+?[\n$]/gm,"").replace(/^\s+(at eval )?at\s+/gm,"").replace(/^([^\(]+?)([\n$])/gm,"{anonymous}()@$1$2").replace(/^Object.<anonymous>\s*\(([^\)]+)\)/gm,"{anonymous}()@$1").split("\n");a.pop();return a},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,"").replace(/^\(/gm,"{anonymous}(").split("\n")},opera11:function(a){var b=/^.*line (\d+), column (\d+)(?: in (.+))? in (\S+):$/;a=a.stacktrace.split("\n");for(var c=
[],d=0,g=a.length;d<g;d+=2){var e=b.exec(a[d]);if(e){var f=e[4]+":"+e[1]+":"+e[2],e=e[3]||"global code",e=e.replace(/<anonymous function: (\S+)>/,"$1").replace(/<anonymous function>/,"{anonymous}");c.push(e+"@"+f+" -- "+a[d+1].replace(/^\s+/,""))}}return c},opera10b:function(a){var b=/^(.*)@(.+):(\d+)$/;a=a.stacktrace.split("\n");for(var c=[],d=0,g=a.length;d<g;d++){var e=b.exec(a[d]);e&&c.push((e[1]?e[1]+"()":"global code")+"@"+e[2]+":"+e[3])}return c},opera10a:function(a){var b=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;
a=a.stacktrace.split("\n");for(var c=[],d=0,g=a.length;d<g;d+=2){var e=b.exec(a[d]);e&&c.push((e[3]||"{anonymous}")+"()@"+e[2]+":"+e[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},opera9:function(a){var b=/Line (\d+).*script (?:in )?(\S+)/i;a=a.message.split("\n");for(var c=[],d=2,g=a.length;d<g;d+=2){var e=b.exec(a[d]);e&&c.push("{anonymous}()@"+e[2]+":"+e[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,c=[],d,g;a&&a.arguments&&10>c.length;)d=
b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",g=Array.prototype.slice.call(a.arguments||[]),c[c.length]=d+"("+this.stringifyArguments(g)+")",a=a.caller;return c},stringifyArguments:function(a){for(var b=[],c=Array.prototype.slice,d=0;d<a.length;++d){var g=a[d];void 0===g?b[d]="undefined":null===g?b[d]="null":g.constructor&&(g.constructor===Array?b[d]=3>g.length?"["+this.stringifyArguments(g)+"]":"["+this.stringifyArguments(c.call(g,0,1))+"..."+this.stringifyArguments(c.call(g,-1))+"]":
g.constructor===Object?b[d]="#object":g.constructor===Function?b[d]="#function":g.constructor===String?b[d]='"'+g+'"':g.constructor===Number&&(b[d]=g))}return b.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();if(b)try{return b.open("GET",a,!1),b.send(null),b.responseText}catch(c){}return""},createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},
function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<b.length;c++)try{return a=b[c](),this.createXMLHTTPObject=b[c],a}catch(d){}},isSameDomain:function(a){return"undefined"!==typeof location&&-1!==a.indexOf(location.hostname)},getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));return this.sourceCache[a]},guessAnonymousFunctions:function(a){for(var b=0;b<a.length;++b){var c=/^(.*?)(?::(\d+))(?::(\d+))?(?: -- .+)?$/,d=a[b],g=/\{anonymous\}\(.*\)@(.*)/.exec(d);
if(g){var e=c.exec(g[1]);e&&(c=e[1],g=e[2],e=e[3]||0,c&&this.isSameDomain(c)&&g&&(c=this.guessAnonymousFunction(c,g,e),a[b]=d.replace("{anonymous}",c)))}}return a},guessAnonymousFunction:function(a,b,c){var d;try{d=this.findFunctionName(this.getSource(a),b)}catch(g){d="getSource failed with url: "+a+", exception: "+g.toString()}return d},findFunctionName:function(a,b){for(var c=/function\s+([^(]*?)\s*\(([^)]*)\)/,d=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*function\b/,g=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*(?:eval|new Function)\b/,
e="",f,h=Math.min(b,20),k,l=0;l<h;++l)if(f=a[b-l-1],k=f.indexOf("//"),0<=k&&(f=f.substr(0,k)),f)if(e=f+e,(f=d.exec(e))&&f[1]||(f=c.exec(e))&&f[1]||(f=g.exec(e))&&f[1])return f[1];return"(?)"}};this.printDebug=f;this.Metadata=x;this.registerObserver=function(a){"undefined"==typeof a&&(a={});var b=a.appId;if("undefined"!=typeof b)"undefined"==typeof h[b]&&(a.platform="html5",h[b]=new r(a));else{b=a.platform;if("undefined"==typeof b){var c=navigator.userAgent.toLowerCase();if(0<=c.indexOf("android"))b=
"android";else if(0<=c.indexOf("ipad")||0<=c.indexOf("iphone")||0<=c.indexOf("ipod"))b="ios"}"android"==b?h[b]=new A(a):"ios"==b&&(h[b]=new B(a))}};if("undefined"!=typeof Crittercism){var z="1.0";try{z=Crittercism.getVersion()}catch(C){}2.3>parseFloat(z)&&(Crittercism=this)}var q=!1;this.init=function(a){try{if(f("init"),!q){q=!0;if(!k){"undefined"!=typeof a.debug&&(w=a.debug);f("Crittercism: LIB_VERSION == "+Crittercism.getVersion());k=!0;var b=window.onerror;window.onerror=function(a,c,e,f,h){try{var k=
u(l({e:h||a,guess:!0}));y("Crash",a,k)}catch(m){}b&&b(a,c,e,f,h)};m=a.appId;f("Crittercism appId == "+m);p=new x(m)}Crittercism.registerObserver(a);q=!1}}catch(c){f("Crittercism init CRASHED!!!")}};this.getVersion=function(){return"2.3"};this.getUsername=function(){var a=null;try{f("getUsername"),k?a=p.getUsername():f("Crittercism isn't initialized yet.  Can't getUsername.")}catch(b){f(b)}return a};this.setUsername=function(a){try{if(f("setUsername"),k){if(p.setUsername(a))for(var b in h)h[b].setUsername(a)}else f("Crittercism isn't initialized yet.  Can't setUsername.")}catch(c){f(c)}};
this.getValue=function(a){var b=null;try{f("getValue"),k?b=p.getValue(a):f("Crittercism isn't initialized yet.  Can't getValue.")}catch(c){f(c)}return b};this.setValue=function(a,b){try{if(f("setValue"),k){if(p.setValue(a,b))for(var c in h)h[c].setValue(a,b)}else f("Crittercism isn't initialized yet.  Can't setValue.")}catch(d){f(d)}};this.setMetadata=function(a){try{if(f("setMetadata"),k){if(p.setMetadata(a))for(var b in h)h[b].setMetadata(a)}else f("Crittercism isn't initialized yet.  Can't setMetadata.")}catch(c){f(c)}};
this.leaveBreadcrumb=function(a){try{if(f("leaveBreadcrumb"),k)for(var b in h)h[b].leaveBreadcrumb(a);else f("Crittercism isn't initialized yet.  Can't leaveBreadcrumb.")}catch(c){f(c)}};this.logNetworkRequest=function(a,b,c,d,g,e,l){try{if(f("logNetworkRequest"),k)for(var m in h)h[m].logNetworkRequest(a,b,c,d,g,e,l);else f("Crittercism isn't initialized yet.  Can't logNetworkRequest.")}catch(n){f(n)}};this.logHandledException=function(a){try{if(f("logHandledException"),k){var b=null;if(a&&"string"==
typeof a.name)b=a.name;else{var c="null";if(a){var c=a.constructor.toString(),d=c.indexOf(" "),c=c.substring(d+1),g=c.search(/\W/),c=c.substring(0,g);0<navigator.userAgent.search("Safari")&&endsWith(c,"Constructor")&&(c=c.substring(0,c.length-11))}b=c}c=null;if(a&&"string"==typeof a.message)c=a.message;else if("object"==typeof a){var e,d="{",h;for(h in a)d=d+h+":"+a[h]+"\n";h=e=d+"}";800<e.length&&(h=e.substring(0,800)+"...");c=h}else c=""+a;var m=u(l({e:a,guess:!0}));y(b,c,m)}else f("Crittercism isn't initialized yet.  Can't logHandledException.")}catch(n){f(n)}return this};
this.beginTransaction=function(a){try{if(f("beginTransaction"),k)for(var b in h)h[b].beginTransaction(a);else f("Crittercism isn't initialized yet.  Can't beginTransaction.")}catch(c){f(c)}};this.endTransaction=function(a){try{if(f("endTransaction"),k)for(var b in h)h[b].endTransaction(a);else f("Crittercism isn't initialized yet.  Can't endTransaction.")}catch(c){f(c)}};this.failTransaction=function(a){try{if(f("failTransaction"),k)for(var b in h)h[b].failTransaction(a);else f("Crittercism isn't initialized yet.  Can't failTransaction.")}catch(c){f(c)}};
this.setTransactionValue=function(a,b){try{if(f("setTransactionValue"),k)for(var c in h)h[c].setTransactionValue(a,b);else f("Crittercism isn't initialized yet.  Can't setTransactionValue.")}catch(d){f(d)}}}try{newCrittercism=new CrittercismClass,"undefined"==typeof Crittercism&&(Crittercism=newCrittercism)}catch(e$$43){console.log("Crittercism: Unexpected error while loading library.")};