//Release: 20
//BUILD 53
function CrittercismClass(){function K(a){function b(c){return"string"==typeof c?c:c instanceof String?c.toString():null}this.sendHandledException=function(c,a,f){if("undefined"!=typeof _crttr){c=b(c);a=b(a);var d=null;"object"==typeof f&&(d=f.join("\r\n"));_crttr.logHandledException(c,a,d)}};this.sendUnhandledException=function(c,a,f){"undefined"!=typeof _crttr&&(c=b(c),a=b(a),f=null,"object"==typeof stack&&(f=stack.join("\r\n")),_crttr.logUnhandledException(c,a,f))};this.logNetworkRequest=function(c,
a,f,d,h,m,k){"undefined"!=typeof _crttr&&(c=b(c),a=b(a),f=parseInt(f),d=parseInt(d),h=parseInt(h),m=parseInt(m),k=parseInt(k),_crttr.logNetworkRequest(c,a,f,d,h,m,k))};this.leaveBreadcrumb=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.leaveBreadcrumb(a))};this.setMetadata=function(a){"undefined"!=typeof _crttr&&"object"==typeof a&&_crttr.setMetadata(JSON.stringify(a))};this.setUsername=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.setUsername(a))};this.setValue=function(a,e){if("undefined"!=
typeof _crttr){b(a);var d=b(e);_crttr.setMetadata(JSON.stringify({keyStr:d}))}};this.beginTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.beginTransaction(a))};this.endTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.endTransaction(a))};this.failTransaction=function(a){"undefined"!=typeof _crttr&&(a=b(a),_crttr.failTransaction(a))};this.setTransactionValue=function(a,e){if("undefined"!=typeof _crttr){var d=parseInt(e),g=b(a);d&&_crttr.setTransactionValue(g,d)}};
this.getTransactionValue=function(a){return"undefined"!=typeof _crttr?(a=b(a),_crttr.getTransactionValue(a)):-1}}function L(a){function b(a){a=JSON.stringify(a);c.src="com.crittercism://eval/"+encodeURIComponent(a)}var c=document.createElement("iframe");c.style.display="none";document.documentElement.appendChild(c);this.sendHandledException=function(a,c,d){d=d.join("\n");b(["logHandledException",a,c,d,2])};this.sendUnhandledException=function(a,c,d){d=d.join("\n");b(["logUnhandledException",a,c,d,
2])};this.logNetworkRequest=function(a,c,d,h,m,k,l){b(["logNetworkRequest",a,c,.001*d,h,m,k,l])};this.leaveBreadcrumb=function(a){b(["leaveBreadcrumb",a])};this.setUsername=function(a){b(["setUsername",a])};this.setValue=function(a,c){b(["setValue",c,a])};this.setMetadata=function(a){};this.beginTransaction=function(a){b(["beginTransaction",a])};this.endTransaction=function(a){b(["endTransaction",a])};this.failTransaction=function(a){b(["failTransaction",a])};this.setTransactionValue=function(a,c){b(["setTransactionValue",
a,c])};this.getTransactionValue=function(a){return-1}}function s(a){function b(){return"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".replace(/[x]/g,function(a){return Math.floor(16*Math.random()).toString(16)})}function c(a){this.isValidAppId=!1;if(a&&null!==a.match(/^[a-f0-9]{24,40}$/gi)){if(24===a.length)a="crittercism.com";else if(40===a.length)switch(a=a.substring(32),a){case "00555300":a="crittercism.com";break;case "00555304":a="crit-ci.com";break;case "00555305":a="crit-staging.com";break;case "00444503":a=
"de.crittercism.com";break;default:return}else return;this.isValidAppId=!0;this.configuredApiUrl="https://api."+a;this.configuredApmUrl="https://apm."+a;this.configuredTxnUrl="https://txn.ingest."+a}else d("Not a valid Crittercism appId == "+a)}function e(){var a=n("breadcrumbs");a||(a="[]");try{this.previous_session=JSON.parse(a)}catch(c){d("Exception occurred while parsing previous session breadcrumb"),d(a),this.previous_session=[]}this.current_session=[];this.leaveBreadcrumb=function(a){if("string"!=
typeof a)throw Error("Invalid breadcrumb type; must be a string");d(a);a=a.substr(0,140);100<=this.current_session.length&&this.current_session.splice(1,1);this.current_session.push([a,t(new Date)]);u("breadcrumbs",JSON.stringify(this.current_session))};this.leaveBreadcrumb("session_start")}function f(){var a=n("network");a||(a="[]");try{this.endpoints=JSON.parse(a)}catch(c){console.log("Crittercism network endpoints from previous session could not be parsed")}this.endpoints.constructor!==Array&&
(this.endpoints=[]);this.logNetworkRequest=function(a,c,b,e,d,f,h){if(!(-1<c.indexOf(y))){var M=t(new Date);100<=this.endpoints.length&&this.endpoints.splice(0,1);this.endpoints.push([a,c,M,b,2,e,d,f,4,h]);u("network",JSON.stringify(this.endpoints));null===D&&(D=window.setTimeout(g,1E4,this))}};this.clearEndpoints=function(){this.endpoints=[];try{localStorage.removeItem(l("network"))}catch(a){}}}function g(a){var c,b;if(0<a.endpoints.length){c=a.endpoints.slice(0);a.clearEndpoints();a=[q,z,E,"2.4",
v];var e=b="UNKNOWN";if("undefined"!=typeof navigator){try{b=navigator.platform}catch(f){}try{e=navigator.userAgent}catch(g){}}var h=t(new Date);d("report_timestamp == "+h);b=[h,"UNKNOWN",b,"html5",e];c={d:[a,b,c]};d("SENDING REPORT TO APM: "+y+"/api/apm/network");d(JSON.stringify(c));k(y+"/api/apm/network",JSON.stringify(c),"application/json;charset=UTF-8")}D=null}function h(a,c){var b=1,e=new Date;this.tryEvent=function(){var d=new Date,f=d-e;e=d;b+=a/c*f;b>a&&(b=a);return 1<=b?(b-=1,!0):!1}}function m(){u("lastSeen",
(new Date).toString())}function k(a,b,c){if(a&&b){var e=!1;if(window.XMLHttpRequest)e=new XMLHttpRequest,e.overrideMimeType&&e.overrideMimeType(c);else if(window.ActiveXObject)try{e=new ActiveXObject("Msxml2.XMLHTTP")}catch(d){try{e=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){}}if(!e)return!1;e.open("POST",a,!0);-1<a.indexOf(w)?e.withCredentials=!0:e.withCredentials=!1;e.setRequestHeader("Content-type",c);e.send(b)}}function l(a){return"com.crittercism.html5/"+q+"/"+a}function n(a){var b=null;
try{b=localStorage.getItem(l(a))}catch(c){}return b}function u(a,b){try{localStorage.setItem(l(a),b)}catch(c){}}function r(){if(s.tryEvent()){var a=JSON.stringify(p);k(w+"/metadata",a,"application/json;charset=UTF-8")}}var E="UNKNOWN",v=0,z=null,A=null,w=null,y=null,B=null,C=null,D=null,s=null,x=null;this.getBreadcrumbs=function(){return B};this.AppLocator=c;this.Breadcrumbs=e;this.Throttle=h;this.sendHandledException=function(a,b,c){x.tryEvent()&&(k(w+"/errors",JSON.stringify({app_id:q,library_version:"2.4",
exceptions:[{library_version:"2.4",exception_name:a,exception_reason:b,breadcrumbs:B,state:{app_version:z},unsymbolized_stacktrace:c}]}),"application/json;charset=UTF-8"),m())};this.sendUnhandledException=function(a,b,c){m()};this.logNetworkRequest=function(a,b,c,e,d,f,g){C.logNetworkRequest(a,b,c,e,d,f,g);m()};this.leaveBreadcrumb=function(a){B.leaveBreadcrumb(a);m()};this.setUsername=function(a){r();m()};this.setValue=function(a,b){r();m()};this.setMetadata=function(a){r();m()};this.beginTransaction=
function(a){m()};this.endTransaction=function(a){m()};this.failTransaction=function(a){m()};this.setTransactionValue=function(a,b){m()};this.getTransactionValue=function(a){m();return-1};(function(a){z=a.appVersion||"unspecified";A=new c(q);if(A.isValidAppId)w=A.configuredApiUrl,y=A.configuredApmUrl;else throw Error("Crittercism is disabled because appId '"+q+"' is invalid");B=new e;s=new h(5,6E4);x=new h(5,6E4);C=new f;var l=n("deviceId");null===l&&(l=b(),u("deviceId",l),l=n("deviceId"),null===l&&
(l="UNKNOWN"));E=l;d("deviceId == "+E);l=n("sessionId");v=l=null===l?0:parseInt(l);l=!0;if(!a.appLoad){a=null;var p=n("lastSeen");p&&(a=new Date(p));a&&(l=18E5<=new Date-a)}l&&(d("sendAppLoad"),v+=1,u("sessionId",v),l=JSON.stringify({app_id:q,library_version:"2.4",app_state:{app_version:z}}),k(w+"/app_loads",l,"application/json;charset=UTF-8"));0<C.endpoints.length&&g(C);m()})(a)}function n(a){a=a||{guess:!0};var b=a.e||null;a=!!a.guess;var c=new n.implementation,b=c.run(b);return a?c.guessAnonymousFunctions(b):
b}function x(a){for(var b=[],c=[/^crittercismErrorHandler/i,/^printStackTrace/i],e=0,d=a.length;e<d;e++){for(var g=a[e],h=!1,l=0,k=c.length;l<k;l++)if(g.match(c[l])){h=!0;break}h||b.push(g)}return b}function d(a){F&&window.console.log("[Crittercism] "+a)}function t(a){function b(a){return 10>a?"0"+a:a}return a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+(a.getUTCMilliseconds()/1E3).toFixed(3).slice(2,
5)+"Z"}function G(){function a(){for(var a,b=[function(){return window.XMLHttpRequest},function(){return window.ActiveXObject("Msxml2.XMLHTTP")},function(){return window.ActiveXObject("Msxml3.XMLHTTP")},function(){return window.ActiveXObject("Microsoft.XMLHTTP")}],d=0;d<b.length;d++)try{return a=b[d](),new a,a}catch(g){}console.log("Unknown XMLHttpRequest, Crittercism service monitoring will be disabled");return null}function b(a){var e=0;try{a&&("string"==typeof a?e=a.length:a.byteLength?e=a.byteLength:
a.size?e=a.size:window.jQuery||(e=b(a.toString())))}catch(d){}return e}d("APM");(function(){var c=a();c?"undefined"==typeof c.prototype._cr_wrapped&&(c.prototype._cr_wrapped=!0,c.prototype._cr_saved_open=c.prototype.open,c.prototype.open=function(){this._cr_stats||(this._cr_stats={method:"",url:"",latency:0,bytesRead:0,bytesSent:0,responseCode:0,errorCode:0});this._cr_saved_open.apply(this,arguments);this._cr_stats.method=arguments[0];this._cr_stats.url=arguments[1]},c.prototype._cr_saved_send=c.prototype.send,
c.prototype.send=function(a){this._cr_stats||(this._cr_stats={method:"",url:"",latency:0,bytesRead:0,bytesSent:0,responseCode:0,errorCode:0});this._cr_stats._currentTime=(new Date).getTime();this._cr_logLatency=function(){this._cr_stats&&this._cr_stats._currentTime&&(this._cr_stats.latency=(new Date).getTime()-this._cr_stats._currentTime)};this._cr_logResponse=function(){this._cr_stats&&(this._cr_stats.responseCode=this.status,this._cr_stats.bytesRead=b(this.response),this._cr_stats.time_stamp=t(new Date),
this._cr_logLatency())};this._cr_saved_onabort=this.onabort;this.onabort=function(){this._cr_errorCode=602;this._cr_saved_onabort&&this._cr_saved_onabort.apply(this,arguments)};this._cr_saved_onerror=this.onerror;this.onerror=function(a){this._cr_errorCode=601;this._cr_saved_onerror&&this._cr_saved_onerror.apply(this,arguments)};this._cr_saved_onloadend=this.onloadend;this.onloadend=function(){this._cr_logResponse();this._cr_errorCode&&(this._cr_stats.errorCode=this._cr_errorCode);this._cr_logLatency();
Crittercism.logNetworkRequest(this._cr_stats.method,this._cr_stats.url,this._cr_stats.latency,this._cr_stats.bytesRead,this._cr_stats.bytesSent,this._cr_stats.responseCode,this._cr_stats.errorCode);this._cr_saved_onloadend&&this._cr_saved_onloadend.apply(this,arguments)};this._cr_saved_onprogress=this.onprogress;this.onprogress=function(){this._cr_logLatency();this._cr_saved_onprogress&&this._cr_saved_onprogress.apply(this,arguments)};this._cr_saved_ontimeout=this.ontimeout;this.ontimeout=function(){this._cr_errorCode=
603;this._cr_saved_ontimeout&&this._cr_saved_ontimeout.apply(this,arguments)};this._cr_saved_onreadystatechange=this.onreadystatechange;this.onreadystatechange=function(){2!=this.readyState&&3!=this.readyState||this._cr_logLatency();4==this.readyState&&this._cr_logResponse();this._cr_saved_onreadystatechange&&this._cr_saved_onreadystatechange.apply(this,arguments)};this._cr_stats.bytesSent=b(a);this._cr_saved_send.apply(this,arguments)}):d("Warning: XMLHttpRequest missing. Crittercism service monitoring will not be installed.")})()}
function H(a){this.app_id=a;this.metadata={};this.setMetadata=function(a){var c,e=!1;if("object"!=typeof a)return d("Crittercism setMetadata given a parameter that is not an object: "+a),!1;this.metadata.username&&!a.username&&(a.username=this.metadata.username);for(c in this.metadata)a.hasOwnProperty(c)||(delete this.metadata[c],e=!0);for(c in a)a.hasOwnProperty(c)&&this.setValue(c,a[c])&&(e=!0);return e};this.setValue=function(a,c){if("string"!=typeof a)return d("Crittercism setValue given a key that is not a string: "+
a),!1;if("string"!=typeof c&&"number"!=typeof c)return d("Crittercism setValue given a value that is not a string or a number: "+c),!1;var e=this.metadata[a]!==c;this.metadata[a]=c;return e};this.getValue=function(a){return"string"!=typeof a?(d("Crittercism getValue given a key that is not a string: "+a),null):this.metadata[a]};this.setUsername=function(a){return"string"!=typeof a?(d("Crittercism setUsername given a name that is not a string: "+a),!1):this.setValue("username",a)};this.getUsername=
function(){return this.getValue("username")}}function I(a,b,c){d("sendHandledException");if(l)for(var e in k)k[e].sendHandledException(a,b,c);else d("Crittercism isn't initialized yet.  Can't sendHandledException.")}var q=null,l=!1,F=!0,p,k={};this.getObserver=function(a){return k[a]};this.getObservers=function(){return k};this.Html5Observer=s;n.implementation=function(){};n.implementation.prototype={run:function(a,b){a=a||this.createException();b=b||this.mode(a);return"other"===b?this.other(arguments.callee):
this[b](a)},createException:function(){try{this.undef()}catch(a){return a}},mode:function(a){return a.arguments&&a.stack?"chrome":"string"===typeof a.message&&"undefined"!==typeof window&&window.opera?!a.stacktrace||-1<a.message.indexOf("\n")&&a.message.split("\n").length>a.stacktrace.split("\n").length?"opera9":a.stack?0>a.stacktrace.indexOf("called from line")?"opera10b":"opera11":"opera10a":a.stack?"firefox":"other"},instrumentFunction:function(a,b,c){a=a||window;var e=a[b];a[b]=function(){c.call(this,
n().slice(4));return a[b]._instrumented.apply(this,arguments)};a[b]._instrumented=e},deinstrumentFunction:function(a,b){a[b].constructor===Function&&a[b]._instrumented&&a[b]._instrumented.constructor===Function&&(a[b]=a[b]._instrumented)},chrome:function(a){a=(a.stack+"\n").replace(/^\S[^\(]+?[\n$]/gm,"").replace(/^\s+(at eval )?at\s+/gm,"").replace(/^([^\(]+?)([\n$])/gm,"{anonymous}()@$1$2").replace(/^Object.<anonymous>\s*\(([^\)]+)\)/gm,"{anonymous}()@$1").split("\n");a.pop();return a},firefox:function(a){return a.stack.replace(/(?:\n@:0)?\s+$/m,
"").replace(/^\(/gm,"{anonymous}(").split("\n")},opera11:function(a){var b=/^.*line (\d+), column (\d+)(?: in (.+))? in (\S+):$/;a=a.stacktrace.split("\n");for(var c=[],e=0,d=a.length;e<d;e+=2){var g=b.exec(a[e]);if(g){var h=g[4]+":"+g[1]+":"+g[2],g=g[3]||"global code",g=g.replace(/<anonymous function: (\S+)>/,"$1").replace(/<anonymous function>/,"{anonymous}");c.push(g+"@"+h+" -- "+a[e+1].replace(/^\s+/,""))}}return c},opera10b:function(a){var b=/^(.*)@(.+):(\d+)$/;a=a.stacktrace.split("\n");for(var c=
[],d=0,f=a.length;d<f;d++){var g=b.exec(a[d]);g&&c.push((g[1]?g[1]+"()":"global code")+"@"+g[2]+":"+g[3])}return c},opera10a:function(a){var b=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;a=a.stacktrace.split("\n");for(var c=[],d=0,f=a.length;d<f;d+=2){var g=b.exec(a[d]);g&&c.push((g[3]||"{anonymous}")+"()@"+g[2]+":"+g[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},opera9:function(a){var b=/Line (\d+).*script (?:in )?(\S+)/i;a=a.message.split("\n");for(var c=[],d=2,f=a.length;d<f;d+=
2){var g=b.exec(a[d]);g&&c.push("{anonymous}()@"+g[2]+":"+g[1]+" -- "+a[d+1].replace(/^\s+/,""))}return c},other:function(a){for(var b=/function\s*([\w\-$]+)?\s*\(/i,c=[],d,f;a&&a.arguments&&10>c.length;)d=b.test(a.toString())?RegExp.$1||"{anonymous}":"{anonymous}",f=Array.prototype.slice.call(a.arguments||[]),c[c.length]=d+"("+this.stringifyArguments(f)+")",a=a.caller;return c},stringifyArguments:function(a){for(var b=[],c=Array.prototype.slice,d=0;d<a.length;++d){var f=a[d];void 0===f?b[d]="undefined":
null===f?b[d]="null":f.constructor&&(f.constructor===Array?b[d]=3>f.length?"["+this.stringifyArguments(f)+"]":"["+this.stringifyArguments(c.call(f,0,1))+"..."+this.stringifyArguments(c.call(f,-1))+"]":f.constructor===Object?b[d]="#object":f.constructor===Function?b[d]="#function":f.constructor===String?b[d]='"'+f+'"':f.constructor===Number&&(b[d]=f))}return b.join(",")},sourceCache:{},ajax:function(a){var b=this.createXMLHTTPObject();if(b)try{return b.open("GET",a,!1),b.send(null),b.responseText}catch(c){}return""},
createXMLHTTPObject:function(){for(var a,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=0;c<b.length;c++)try{return a=b[c](),this.createXMLHTTPObject=b[c],a}catch(d){}},isSameDomain:function(a){return"undefined"!==typeof location&&-1!==a.indexOf(location.hostname)},getSource:function(a){a in this.sourceCache||(this.sourceCache[a]=this.ajax(a).split("\n"));
return this.sourceCache[a]},guessAnonymousFunctions:function(a){for(var b=0;b<a.length;++b){var c=/^(.*?)(?::(\d+))(?::(\d+))?(?: -- .+)?$/,d=a[b],f=/\{anonymous\}\(.*\)@(.*)/.exec(d);if(f){var g=c.exec(f[1]);g&&(c=g[1],f=g[2],g=g[3]||0,c&&this.isSameDomain(c)&&f&&(c=this.guessAnonymousFunction(c,f,g),a[b]=d.replace("{anonymous}",c)))}}return a},guessAnonymousFunction:function(a,b,c){var d;try{d=this.findFunctionName(this.getSource(a),b)}catch(f){d="getSource failed with url: "+a+", exception: "+
f.toString()}return d},findFunctionName:function(a,b){for(var c=/function\s+([^(]*?)\s*\(([^)]*)\)/,d=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*function\b/,f=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*(?:eval|new Function)\b/,g="",h,l=Math.min(b,20),k,n=0;n<l;++n)if(h=a[b-n-1],k=h.indexOf("//"),0<=k&&(h=h.substr(0,k)),h)if(g=h+g,(h=d.exec(g))&&h[1]||(h=c.exec(g))&&h[1]||(h=f.exec(g))&&h[1])return h[1];return"(?)"}};this.printDebug=d;this.dateToISOString=t;this.APM=G;this.Metadata=H;this.registerObserver=function(a){"undefined"==
typeof a&&(a={});var b=a.appId;if("undefined"!=typeof b)a.platform="html5",k[b]=new s(a);else{b=a.platform;if("undefined"==typeof b){var c="UNKNOWN";if("undefined"!=typeof navigator)try{c=navigator.userAgent.toLowerCase()}catch(d){}if(0<=c.indexOf("android"))b="android";else if(0<=c.indexOf("ipad")||0<=c.indexOf("iphone")||0<=c.indexOf("ipod"))b="ios"}"android"==b?k[b]=new K(a):"ios"==b&&(k[b]=new L(a))}};if("undefined"!=typeof Crittercism){var J="1.0";try{J=Crittercism.getVersion()}catch(N){}2.4>
parseFloat(J)&&(Crittercism=this)}var r=!1;this.init=function(a){try{if(d("init"),!r){r=!0;if(!l){"undefined"!=typeof a.debug&&(F=a.debug);d("LIB_VERSION == "+Crittercism.getVersion());l=!0;var b=window.onerror;window.onerror=function(a,c,d,h,l){try{var k=x(n({e:l||a,guess:!0}));I("Crash",a,k)}catch(p){}b&&b(a,c,d,h,l)};q=a.appId;d("Crittercism appId == "+q);new G;p=new H(q)}Crittercism.registerObserver(a);r=!1}}catch(c){d(""+c),d("Crittercism init CRASHED!!!")}};this.getVersion=function(){return"2.4"};
this.getUsername=function(){var a=null;try{d("getUsername"),l?a=p.getUsername():d("Crittercism isn't initialized yet.  Can't getUsername.")}catch(b){d(b)}return a};this.setUsername=function(a){try{if(d("setUsername"),l){if(p.setUsername(a))for(var b in k)k[b].setUsername(a)}else d("Crittercism isn't initialized yet.  Can't setUsername.")}catch(c){d(c)}};this.getValue=function(a){var b=null;try{d("getValue"),l?b=p.getValue(a):d("Crittercism isn't initialized yet.  Can't getValue.")}catch(c){d(c)}return b};
this.setValue=function(a,b){try{if(d("setValue"),l){if(p.setValue(a,b))for(var c in k)k[c].setValue(a,b)}else d("Crittercism isn't initialized yet.  Can't setValue.")}catch(e){d(e)}};this.setMetadata=function(a){try{if(d("setMetadata"),l){if(p.setMetadata(a))for(var b in k)k[b].setMetadata(a)}else d("Crittercism isn't initialized yet.  Can't setMetadata.")}catch(c){d(c)}};this.leaveBreadcrumb=function(a){try{if(d("leaveBreadcrumb"),l)for(var b in k)k[b].leaveBreadcrumb(a);else d("Crittercism isn't initialized yet.  Can't leaveBreadcrumb.")}catch(c){d(c)}};
this.logNetworkRequest=function(a,b,c,e,f,g,h){try{if(d("logNetworkRequest"),d(b),l)if("string"!=typeof a)d("error: method == "+a+"should be a string");else if("string"!=typeof b)d("error: url == "+b+"should be a string");else{0>"GET HEAD POST PUT DELETE TRACE OPTIONS CONNECT PATCH".split(" ").indexOf(a.toUpperCase())&&d("warning: method == "+a+"should be an HTTP verb ('GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'TRACE', 'OPTIONS', 'CONNECT', 'PATCH')");"number"!=typeof c?(d("warning: latency == "+c+
"should be a number"),c=0):0>c&&d("warning: latency == "+c+"should be >= 0");"number"!=typeof e?(d("warning: bytesRead == "+e+"should be a number"),e=0):0>e&&d("warning: bytesRead == "+e+"should be >= 0");"number"!=typeof f?(d("warning: bytesSent == "+f+"should be a number"),f=0):0>f&&d("warning: bytesSent == "+f+"should be >= 0");"number"!=typeof g?(d("warning: responseCode == "+g+"should be a number"),g=0):0===h&&(100>g||599<=g)&&d("warning: responseCode == "+g+"should be inside 100-599 for errorCode == 0");
h?"number"!=typeof h?(d("warning: errorCode == "+h+"should be a number"),h=0):0!==h&&0!==g&&d("warning: errorCode == "+h+"should be 0 for errorCode != 0"):h=0;for(var m in k)k[m].logNetworkRequest(a,b,c,e,f,g,h)}else d("Crittercism isn't initialized yet.  Can't logNetworkRequest.")}catch(n){d(n)}};this.logHandledException=function(a){try{if(d("logHandledException"),l){var b=null;if(a&&"string"==typeof a.name)b=a.name;else{var c="null";if(a){var c=a.constructor.toString(),e=c.indexOf(" "),c=c.substring(e+
1),f=c.search(/\W/),c=c.substring(0,f);try{"undefined"!=typeof navigator&&0<navigator.userAgent.search("Safari")&&endsWith(c,"Constructor")&&(c=c.substring(0,c.length-11))}catch(g){}}b=c}c=null;if(a&&"string"==typeof a.message)c=a.message;else if("object"==typeof a){var h,e="{",k;for(k in a)e=e+k+":"+a[k]+"\n";k=h=e+"}";800<h.length&&(k=h.substring(0,800)+"...");c=k}else c=""+a;var p=x(n({e:a,guess:!0}));d(b);d(c);d(p);I(b,c,p)}else d("Crittercism isn't initialized yet.  Can't logHandledException.")}catch(q){d(q)}return this};
this.beginTransaction=function(a){try{if(d("beginTransaction"),l)for(var b in k)k[b].beginTransaction(a);else d("Crittercism isn't initialized yet.  Can't beginTransaction.")}catch(c){d(c)}};this.endTransaction=function(a){try{if(d("endTransaction"),l)for(var b in k)k[b].endTransaction(a);else d("Crittercism isn't initialized yet.  Can't endTransaction.")}catch(c){d(c)}};this.failTransaction=function(a){try{if(d("failTransaction"),l)for(var b in k)k[b].failTransaction(a);else d("Crittercism isn't initialized yet.  Can't failTransaction.")}catch(c){d(c)}};
this.setTransactionValue=function(a,b){try{if(d("setTransactionValue"),l)for(var c in k)k[c].setTransactionValue(a,b);else d("Crittercism isn't initialized yet.  Can't setTransactionValue.")}catch(e){d(e)}}}try{newCrittercism=new CrittercismClass,"undefined"==typeof Crittercism&&(Crittercism=newCrittercism,"undefined"!=typeof module&&(module.exports=Crittercism))}catch(e$$48){console.log("[Crittercism] error: "+e$$48),console.log("[Crittercism] error: Unexpected error while loading library.")};