<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
	"frontText": {
		"samplekey": "samplevalue"
	},
	"linkPaths": {
		"home": "/main_phone.do",
		"cart": "/mylotte/cart/m/cart_list.do",
		"login": "/login/m/loginForm.do",
		"logout": "/login/logout.do",
		"company": "/agreement/company.do",
		"custAgreement": "/agreement/custAgreement.do",
		"custPrivacy": "/agreement/custPrivacy.do",
		"protectYouth": "/agreement/protect_youth.do"
	},
	"linkUrls": {
		"bizinfo": "http://www.ftc.go.kr/info/bizinfo/coomunicationList.jsp",
		"guarantee": "http://www.lotte.com/main/common/forward.GuaranteeService_pop.lotte"
	},
	"footerText": {
		"ownerName":"김경호",
		"youthProtectionName":"김찬기",
		"privacyName":"임성묵"
	},
	"hideHeaderBar": [
		"/category/m/brand_search.do",
		"/search/m/mobile_search_list.do",
		"/talk/main/talk_main.do",
		"/talk/main/Samanda_main.do",
        "/talk/main/talkShopping.do",
		"/product/m/product_detail_new.do",
		"/search/m/custom_search.do",
		"/product/m/sub/product_benefit_compare.do",
		"/product/m/sub/product_collect_benefits.do",
		"/product/m/sub/product_comment.do",
		"/product/m/sub/product_comment_detail.do",
		"/product/m/sub/product_comment_image_detail.do",
		"/product/m/sub/product_comment_image.do",
		"/product/m/sub/product_comment_each.do",
		"/product/m/sub/product_ext_info.do",
		"/product/m/sub/product_image_view.do",
		"/product/m/sub/product_qna.do",
		"/product/m/sub/product_req_info.do",
		"/talk/main/voiceCommerce.do",
		"/popup/talk_base_pay.do",
		"/popup/talk_delivery_service.do",
		"/popup/ord_search_address_new.do",
		"/mylotte/profile/m/mylotte_profile.do"
	],
	"hideActionBar": [
		"/product/m/product_view.do",
		"/product/m/product_wine_view.do",
        "/product/m/product_view_gucci.do", 
        "/order/m/order_form.do", 
        "/mylotte/cart/m/cart_list.do", 
        "/custcenter/m/question.do", 
        "/product/product_quest_write.do", 
        "/product/product_quest_write_gucci.do", 
        "/product/m/product_detail_new.do", 
        "/smartpick/pick_list.do", 
        "/smartpick/pick_gift.do", 
        "/smartpick/smp_cpn_info.do", 
        "/talk/main/talk_main.do", 
        "/talk/cart/talk_service_cart.do", 
        "/talk/purchase/talk_service_purchase.do", 
        "/talk/main/knowConsult.do", 
        "/talk/alarm/alarmSetting.do", 
        "/talk/main/Samanda_main.do",
        "/talk/main/talkShopping.do",
        "/popup/talk_delivery_service.do",
        "/login/m/b2bLogin.do", 
        "/mall/sslive.do",
        "/category/m/brand_search.do",
        "/smartpick/m/smartpick_booking.do",
		"/product/m/sub/product_benefit_compare.do",
		"/product/m/sub/product_collect_benefits.do",
		"/product/m/sub/product_comment.do",
		"/product/m/sub/product_comment_detail.do",
		"/product/m/sub/product_ext_info.do",
		"/product/m/sub/product_image_view.do",
		"/product/m/sub/product_qna.do",
		"/product/m/sub/product_req_info.do",
		"/product/m/product_view_burberry.do",
		"/talk/main/voiceCommerce.do",
		"/popup/talk_base_pay.do",
		"/talk/voice_order.do",
		"https://m.pay.naver.com/payments/",
		"https://nid.naver.com",
		"/mylotte/profile/m/mylotte_profile.do",
		"/mylotte/product/m/mylotte_favorites_reviewer.do"
	],
	"superbnr_exclude_keyword" : "/jsondata/superbnr_exclude_keyword.do",
	"appSnsTitle" : "[롯데닷컴]",
	"footerText_new": {
		"type0Name":"법인명",
		"type0Value":"<strong>롯데쇼핑(주) e커머스 사업본부</strong>",
		"type1Name":"회사소개",
		"type1Value":"http://company.lotte.com/mobile/index.lotte",
		"type2Name":"사업자정보확인",
		"type2Value":"http://www.ftc.go.kr/info/bizinfo/communicationViewPopup.jsp?wrkr_no=5298500774",
		"type3Name":"",
		"type3Value":"",
		"type4Name":"대표이사",
		"type4Value":"강희태",
		"type5Name":"주소",
		"type5Value":"서울시 중구 을지로 158 8층(을지로4가, 삼풍빌딩)",
		"type6Name":"사업자등록번호",
		"type6Value":"529-85-00774",
		"type7Name":"통신판매업 신고",
		"type7Value":"서울중구 제1226호",
		"type8Name":"고객만족센터",
		"type8Value":"1577-1110",
		"type9Name":"이메일",
		"type9Value":"webmaster@lotte.com",
		"type10Name":"개인정보보호책임자",
		"type10Value":"임성묵",
		"type11Name":"청소년보호책임자",
		"type11Value":"김찬기",
		"type12Name":"호스팅 사업자",
		"type12Value":"롯데쇼핑(주) e커머스 사업본부",
		"type13Name":"이용약관",
		"type13Value":"/agreement/custAgreement.do?tclick=m_DC_footer_Clk_Lnk_10",
		"type14Name":"<strong>개인정보처리방침</strong>",
		"type14Value":"/agreement/custPrivacy.do?tclick=m_DC_footer_Clk_Lnk_11",
		"type15Name":"청소년보호정책",
		"type15Value":"/agreement/protect_youth.do?tclick=m_DC_footer_Clk_Lnk_12",
		"type16Name":"앱알림 설정안내",
		"type16Value":"",
		"type17Name":"저작권",
		"type17Value":"Copyright ⓒ LOTTESHOPPING Co., LTD. All rights Reserved.",
		"type18Name":"슬로건",
		"type18Value":"http://image.lotte.com/lotte/mo2017/common/f_txt_renewer2018.png",
		"type19Name":"소비자피해보상보험",
		"type19Value":"서울보증보험",
		"type18Width":"",
		"type18Height":""
	}
}