<%@ page contentType="application/json; charset=UTF-8" %>
<%
int dispNo = Integer.parseInt(request.getParameter("dispNo"));
%>
{
  "kShop" : {
    "banners" : {
      "items" : [ {
        "alt" : "엣지룩",
        "imgUrl" : "http://image.lotte.com/upload/display/corner/5535841_42956_40972_30_13008070_13.jpg",
        "linkUrl" : "/product/m/product_list.do?curDispNo=5388618&tclick=K_THEME_05"
      }, {
        "alt" : "식품통합전",
        "imgUrl" : "http://image.lotte.com/upload/display/corner/5535841_42956_40972_30_13008070_10.jpg",
        "linkUrl" : "/product/m/product_list.do?curDispNo=5388095&tclick=K_THEME_05"
      }, {
        "alt" : "노블디바이스",
        "imgUrl" : "http://image.lotte.com/upload/display/corner/5535841_42956_40972_30_13008070_8.jpg",
        "linkUrl" : "/product/m/product_list.do?curDispNo=5389436&tclick=K_THEME_05"
      }, {
        "alt" : "뷰티통합전",
        "imgUrl" : "http://image.lotte.com/upload/display/corner/5535841_42956_40972_30_13008070_15.jpg",
        "linkUrl" : "/product/m/product_list.do?curDispNo=5388925&tclick=K_THEME_05"
      }, {
        "alt" : "노블디바이스",
        "imgUrl" : "http://image.lotte.com/upload/display/corner/5535841_42956_40972_30_13008070_8.jpg",
        "linkUrl" : "/product/m/product_list.do?curDispNo=5389436&tclick=K_THEME_05"
      } ],
      "total_count" : 5
    },
    "prdList" : {
      "items" : [ {
        "ctgName" : "Edge Look",
        "product" : [ {
          "goods_no" : 243211085,
          "disp_no" : 5408063,
          "goods_nm" : "[르마스크] 클래시 미니크로스백 외 10종",
          "brnd_nm" : "르마스크",
          "img_url" : "http://image.lotte.com/goods/85/10/21/43/2/243211085_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/85/10/21/43/2/243211085_1_550.jpg",
          "original_price" : 59000,
          "discounted_price" : 48380,
          "sale_rate" : 18,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : true,
          "has_wish" : false,
          "is_sale_promotion" : true,
          "review_count" : 0,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "0.0",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 18
        }, {
          "goods_no" : 178611492,
          "disp_no" : 5408094,
          "goods_nm" : "플랫아이언 정글 글래머 크로스백 빈티지민트 F1001801BM",
          "brnd_nm" : "플랫아이언",
          "img_url" : "http://image.lotte.com/goods/92/14/61/78/1/178611492_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/92/14/61/78/1/178611492_1_550.jpg",
          "original_price" : 268500,
          "discounted_price" : 267200,
          "sale_rate" : 0,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 0,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "0.0",
          "nint_card_flag" : "무이자6",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        } ]
      }, {
        "ctgName" : "Awesome Beauty",
        "product" : [ {
          "goods_no" : 62262610,
          "disp_no" : 5536045,
          "goods_nm" : "[본사직영] 버블 프리 피에이치 밸런싱 클렌져 1+1(250ml+150ml)+7요일팩 7종",
          "brnd_nm" : "아크웰",
          "img_url" : "http://image.lotte.com/goods/10/26/26/62/62262610_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/10/26/26/62/62262610_1_550.jpg",
          "original_price" : 0,
          "discounted_price" : 35200,
          "sale_rate" : 0,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 13,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "4.8",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        }, {
          "goods_no" : 67007520,
          "disp_no" : 5536044,
          "goods_nm" : "불가리안 로즈 블레미쉬 케어 세럼 플러스 50ml+정품 로즈팩1매",
          "brnd_nm" : "아이소이",
          "img_url" : "http://image.lotte.com/goods/20/75/00/67/67007520_2_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/20/75/00/67/67007520_2_550.jpg",
          "original_price" : 70000,
          "discounted_price" : 56000,
          "sale_rate" : 20,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : true,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 44,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "5.0",
          "nint_card_flag" : "무이자6",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 20
        } ]
      }, {
        "ctgName" : "Creative Living",
        "product" : [ {
          "goods_no" : 295187334,
          "disp_no" : 5394575,
          "goods_nm" : "실리만 BEST 인기상품 모음전",
          "brnd_nm" : "실리만",
          "img_url" : "http://image.lotte.com/goods/34/73/18/95/2/295187334_12_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/34/73/18/95/2/295187334_12_550.jpg",
          "original_price" : 0,
          "discounted_price" : 4200,
          "sale_rate" : 0,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : true,
          "review_count" : 0,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "0.0",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        }, {
          "goods_no" : 81773290,
          "disp_no" : 5424395,
          "goods_nm" : "풀잎 흡착식 항균 칫솔걸이 다용도걸이(4개-1세트)",
          "brnd_nm" : "프리젠트",
          "img_url" : "http://image.lotte.com/goods/90/32/77/81/81773290_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/90/32/77/81/81773290_1_550.jpg",
          "original_price" : 0,
          "discounted_price" : 8700,
          "sale_rate" : 0,
          "benefit_flags" : [ ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 67,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "4.8",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        } ]
      }, {
        "ctgName" : "Novel Devices",
        "product" : [ {
          "goods_no" : 137228028,
          "disp_no" : 5281557,
          "goods_nm" : "CUZET 와이드 전기그릴 670mm 대형사이즈",
          "brnd_nm" : "세한",
          "img_url" : "http://image.lotte.com/goods/28/80/22/37/1/137228028_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/28/80/22/37/1/137228028_1_550.jpg",
          "original_price" : 0,
          "discounted_price" : 69900,
          "sale_rate" : 0,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 0,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "0.0",
          "nint_card_flag" : "무이자6",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        }, {
          "goods_no" : 49214499,
          "disp_no" : 5281666,
          "goods_nm" : "[수동/게르마늄컵7개]요구르트 제조기 NY-E8700",
          "brnd_nm" : "엔유씨",
          "img_url" : "http://image.lotte.com/goods/99/44/21/49/49214499_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/99/44/21/49/49214499_1_550.jpg",
          "original_price" : 60000,
          "discounted_price" : 52200,
          "sale_rate" : 13,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : true,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 13,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "5.0",
          "nint_card_flag" : "무이자6",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 13
        } ]
      }, {
        "ctgName" : "Authentic Food",
        "product" : [ {
          "goods_no" : 52753964,
          "disp_no" : 5395704,
          "goods_nm" : "유기농 양배추즙 2박스(총 60포)",
          "brnd_nm" : "자연의품격",
          "img_url" : "http://image.lotte.com/goods/64/39/75/52/52753964_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/64/39/75/52/52753964_1_550.jpg",
          "original_price" : 0,
          "discounted_price" : 29900,
          "sale_rate" : 0,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : false,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 209,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "4.9",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 0
        }, {
          "goods_no" : 60389741,
          "disp_no" : 5395806,
          "goods_nm" : "순수한 아사이베리 1박스(30포) 아사이베리즙",
          "brnd_nm" : "자연의품격",
          "img_url" : "http://image.lotte.com/goods/41/97/38/60/60389741_1_280.jpg",
          "img_url_550" : "http://image.lotte.com/goods/41/97/38/60/60389741_1_550.jpg",
          "original_price" : 19800,
          "discounted_price" : 19210,
          "sale_rate" : 2,
          "benefit_flags" : [ "sort_icon05" ],
          "mall_flags" : null,
          "flag" : "",
          "is_sold_out" : false,
          "has_coupon" : true,
          "has_wish" : false,
          "is_sale_promotion" : false,
          "review_count" : 282,
          "bought_sum" : 0,
          "md_tip" : null,
          "promotion_text" : null,
          "dlv_fee_tp" : "Y",
          "smartpick_yn" : "N",
          "sold_out_cd_yn" : null,
          "limit_age_yn" : "N",
          "wish_item" : null,
          "parentCatePath" : null,
          "parentCateList" : null,
          "link_url" : null,
          "title_nm" : null,
          "is_himart" : false,
          "is_dept" : false,
          "is_youngplz" : false,
          "isDlvToday" : false,
          "isDeptPickYn" : false,
          "isCrsPickYn" : false,
          "dt_rnk" : null,
          "divobj_no" : "",
          "curDispNo" : "",
          "curDispNoSctCd" : "20",
          "find_age" : null,
          "find_gender" : null,
          "avg_gdas_stfd_val" : "4.9",
          "nint_card_flag" : "",
          "divObjNo" : null,
          "divObjNm" : null,
          "calculatedSaleRate" : 2
        } ]
      } ],
      "total_count" : 5
    },
    "topHtml" : "<ul>\r\n    <li><a href=\"#/info\"><img alt=\"K.SHOP\" src=\"http://image.lotte.com/lotte/mobile/mobile_new/brandshop/kshop/temp_kshop_s_banner01.gif\" /></a>&nbsp;</li>\r\n    <li><a href=\"/product/m/product_list.do?curDispNo=5382645&amp;tclick=M_K_DreamPlaza\"><img alt=\"롯데백화점 드림 플라자\" src=\"http://image.lotte.com/lotte/mobile/mobile_new/brandshop/kshop/temp_kshop_s_banner02.gif\" /></a></li>\r\n    <li><a href=\"/product/m/product_list.do?curDispNo=5383371&amp;tclick=M_K_TogetherShow\"><img alt=\"아임쇼핑\" src=\"http://image.lotte.com/upload/editor/2015/07/03/2459963.gif\" /></a></li>\r\n</ul>",
    <% if(dispNo == 5553048){ %>
    "lotteStore":[
		{"title":"롯데 스토어"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_1.jpg","linkUrl":"5359931"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_2.jpg","linkUrl":"5352357"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_3.jpg","linkUrl":"5396740"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_4.jpg","linkUrl":"5379033"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_5.jpg","linkUrl":"5381332"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_6.jpg","linkUrl":"5371425"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_7.jpg","linkUrl":"5381248"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_8.jpg","linkUrl":"5381351"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_9.jpg","linkUrl":"5371187"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_10.jpg","linkUrl":"5408052"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_11.jpg","linkUrl":"5396735"},
		{"imgUrl":"http:\/\/image.lotte.com\/upload\/display\/corner\/5553048_51355_46761_30_13009603_12.jpg","linkUrl":"5396687"}
	]
    <% }else{ %>
    "lotteStore" : null
    <% } %>
  }
}